/**
 * Phase 1 Milady cosmetics drop — 6 hats + 6 sunglasses.
 *
 * Each SKU is first-party (license_spdx='OWN'), scope='avatar', rendered on
 * Milady VRM avatars only via the cosmetic-loader's HatOrGlassesRenderer.
 * Geometry is generated by apps/web/scripts/generate-cosmetic-glbs.mjs in
 * metric units to match the VRM head-bone-local frame.
 *
 * Run: bun packages/database/scripts/seed-milady-cosmetics.ts
 *
 * Idempotent — re-runs UPSERT by slug.
 */

import postgres from 'postgres';
import { resolve } from 'path';
import { config } from 'dotenv';

config({ path: resolve(__dirname, '../../../.env.local') });

if (!process.env.DATABASE_URL) {
  console.error('DATABASE_URL not set');
  process.exit(1);
}

interface CosmeticSeed {
  slug: string;
  category: 'hat' | 'glasses';
  displayName: string;
  description: string;
  rarity: 'common' | 'rare' | 'epic';
  priceCt: number;
  glbPath: string;
  /** Head-bone-local offset in meters (VRM 1.0 metric). */
  offsetXYZ: [number, number, number];
  /** Scale factor on top of the geometry's authored metric size. */
  scale: number;
  /** Optional rotation in radians (XYZ). */
  rotationXYZ?: [number, number, number];
}

// HATS
// Offsets are tuned for Milady VRM mixamorigHead bone. The bone origin sits
// at the BASE of the skull (where neck meets head), and Milady hair geometry
// extends 12-16cm above it. Hats need to clear the hair, so Y offsets sit
// at +0.16..+0.22m depending on hat brim depth. Re-tune visually if the
// hat clips through hair on a particular Milady variant.
const HATS: CosmeticSeed[] = [
  {
    slug: 'top-hat',
    category: 'hat',
    displayName: 'Top Hat',
    description: 'Classic black silk top hat with a burgundy band. Old money energy.',
    rarity: 'rare',
    priceCt: 600,
    glbPath: '/cosmetics/hats/top-hat.glb',
    offsetXYZ: [0, 0.18, 0],
    scale: 1.0,
  },
  {
    slug: 'cowboy-hat',
    category: 'hat',
    displayName: 'Cowboy Hat',
    description: 'Tan leather cowboy hat. Yeehaw on the chain.',
    rarity: 'common',
    priceCt: 300,
    glbPath: '/cosmetics/hats/cowboy.glb',
    offsetXYZ: [0, 0.18, 0],
    scale: 1.0,
  },
  {
    slug: 'beanie',
    category: 'hat',
    displayName: 'Red Beanie',
    description: 'Knit red beanie with cream pom-pom. Cozy maxi.',
    rarity: 'common',
    priceCt: 300,
    glbPath: '/cosmetics/hats/beanie.glb',
    // Beanie wraps the head — sits LOWER than other hats so it hugs the
    // skull. +0.13 puts the brim at hair-line, dome at crown level.
    offsetXYZ: [0, 0.13, 0],
    scale: 1.0,
  },
  {
    slug: 'wizard-hat',
    category: 'hat',
    displayName: 'Wizard Hat',
    description: 'Tall purple wizard hat with floating gold stars. +5 wisdom.',
    rarity: 'epic',
    priceCt: 1200,
    glbPath: '/cosmetics/hats/wizard.glb',
    offsetXYZ: [0, 0.18, 0],
    scale: 1.0,
  },
  {
    slug: 'royal-crown',
    category: 'hat',
    displayName: 'Royal Crown',
    description: 'Eight-spike gold crown with a single ruby. Coronation tier.',
    rarity: 'epic',
    priceCt: 1200,
    glbPath: '/cosmetics/hats/crown.glb',
    // Crown rests directly on hair — slightly lower than full-brim hats.
    offsetXYZ: [0, 0.15, 0],
    scale: 1.0,
  },
  {
    slug: 'bucket-hat',
    category: 'hat',
    displayName: 'Bucket Hat',
    description: 'Olive bucket hat. Festival-ready, fishing-optional.',
    rarity: 'common',
    priceCt: 300,
    glbPath: '/cosmetics/hats/bucket.glb',
    offsetXYZ: [0, 0.16, 0],
    scale: 1.0,
  },
];

// SUNGLASSES
// Glasses sit forward of head bone origin at eye level: y ≈ +0.04, z ≈ +0.10
// (Mixamo head bone +Z = forward). Empirical — adjust live if needed.
const GLASSES: CosmeticSeed[] = [
  {
    slug: 'classic-black-shades',
    category: 'glasses',
    displayName: 'Classic Black Shades',
    description: 'Timeless wayfarer-style black sunglasses.',
    rarity: 'common',
    priceCt: 300,
    glbPath: '/cosmetics/glasses/classic-black.glb',
    offsetXYZ: [0, 0.04, 0.09],
    scale: 1.0,
  },
  {
    slug: 'rose-gold-shades',
    category: 'glasses',
    displayName: 'Rose Gold Shades',
    description: 'Round rose-gold frames with rosé-tinted lenses.',
    rarity: 'rare',
    priceCt: 600,
    glbPath: '/cosmetics/glasses/rose-gold.glb',
    offsetXYZ: [0, 0.04, 0.09],
    scale: 1.0,
  },
  {
    slug: 'aviator-shades',
    category: 'glasses',
    displayName: 'Aviator Shades',
    description: 'Brass aviator frames. Top Gun vibes.',
    rarity: 'common',
    priceCt: 300,
    glbPath: '/cosmetics/glasses/aviator.glb',
    offsetXYZ: [0, 0.04, 0.09],
    scale: 1.0,
  },
  {
    slug: 'cyberpunk-visor',
    category: 'glasses',
    displayName: 'Cyberpunk Visor',
    description: 'Neon cyan rectangular visor. Glow on chain.',
    rarity: 'epic',
    priceCt: 1200,
    glbPath: '/cosmetics/glasses/cyberpunk.glb',
    offsetXYZ: [0, 0.04, 0.09],
    scale: 1.0,
  },
  {
    slug: 'heart-shades',
    category: 'glasses',
    displayName: 'Heart Shades',
    description: 'Pink heart-shaped sunglasses. Lover-girl coded.',
    rarity: 'rare',
    priceCt: 600,
    glbPath: '/cosmetics/glasses/heart.glb',
    offsetXYZ: [0, 0.04, 0.09],
    scale: 1.0,
  },
  {
    slug: 'shutter-shades',
    category: 'glasses',
    displayName: 'Shutter Shades',
    description: 'Yellow venetian-blind shutter shades. 2008 throwback.',
    rarity: 'rare',
    priceCt: 600,
    glbPath: '/cosmetics/glasses/shutter.glb',
    offsetXYZ: [0, 0.04, 0.09],
    scale: 1.0,
  },
];

const ALL: CosmeticSeed[] = [...HATS, ...GLASSES];

const ATTRIBUTION = 'ClawVille first-party';
const ATTRIBUTION_URL = null;
const LICENSE = 'OWN';

const client = postgres(process.env.DATABASE_URL, { max: 1 });

try {
  console.log(`[seed-milady-cosmetics] Upserting ${ALL.length} SKUs + variants…`);

  for (const c of ALL) {
    const [sku] = await client<[{ id: string }]>`
      INSERT INTO cosmetic_skus (
        slug, category, scope, display_name, description, rarity,
        price_ct, attribution, attribution_url, license_spdx
      ) VALUES (
        ${c.slug}, ${c.category}, 'avatar', ${c.displayName},
        ${c.description}, ${c.rarity}, ${c.priceCt},
        ${ATTRIBUTION}, ${ATTRIBUTION_URL}, ${LICENSE}
      )
      ON CONFLICT (slug) DO UPDATE SET
        display_name = EXCLUDED.display_name,
        description = EXCLUDED.description,
        rarity = EXCLUDED.rarity,
        price_ct = EXCLUDED.price_ct,
        category = EXCLUDED.category,
        scope = EXCLUDED.scope,
        attribution = EXCLUDED.attribution,
        license_spdx = EXCLUDED.license_spdx
      RETURNING id
    `;

    const meta: Record<string, unknown> = {
      boneAnchor: 'J_Bip_C_Head',
      offsetXYZ: c.offsetXYZ,
      scale: c.scale,
    };
    if (c.rotationXYZ) meta.rotationXYZ = c.rotationXYZ;

    await client`
      INSERT INTO cosmetic_variants (sku_id, rig_type, asset_url, asset_meta)
      VALUES (
        ${sku.id},
        'milady-vrm',
        ${c.glbPath},
        ${meta}::jsonb
      )
      ON CONFLICT (sku_id, rig_type) DO UPDATE SET
        asset_url = EXCLUDED.asset_url,
        asset_meta = EXCLUDED.asset_meta
    `;

    console.log(`  ✓ ${c.slug.padEnd(24)} (${c.category}, ${c.rarity}, ${c.priceCt} CT)`);
  }

  const skuRows = await client`
    SELECT slug, category, rarity, price_ct
    FROM cosmetic_skus
    WHERE scope = 'avatar' AND license_spdx = 'OWN'
    ORDER BY category, slug
  `;
  console.log(`\n[verify] Seeded ${skuRows.length} avatar SKUs:`);
  for (const r of skuRows) {
    console.log(
      `  - ${(r.slug as string).padEnd(24)} ${(r.category as string).padEnd(8)} ${(r.rarity as string).padEnd(7)} ${r.price_ct} CT`,
    );
  }

  console.log('\n[done] Cosmetics drawer + future shop will pick these up automatically.');
} catch (err) {
  console.error('[seed-milady-cosmetics] FAILED:', err);
  process.exit(1);
} finally {
  await client.end();
}
