import type { MapLocation } from '../types/location';

// Building zones calibrated for the sea-floor map (780x468 actual dimensions)
// 10 OpenClaw integration-themed sea landmarks
export const MAP_LOCATIONS: MapLocation[] = [
  {
    id: 'cron-hub',
    name: 'Tide Clock Grotto',
    description: 'Tick-tock — schedule tasks timed to the ocean currents.',
    icon: '🐚',
    positionX: 80,
    positionY: 60,
    width: 80,
    height: 80,
  },
  {
    id: 'webhook-gateway',
    name: 'Current Gateway',
    description: 'Incoming signals ride the currents — endpoints for the reef.',
    icon: '🌊',
    positionX: 200,
    positionY: 50,
    width: 70,
    height: 70,
  },
  {
    id: 'memory-vault',
    name: 'Abyssal Vault',
    description: 'Deep-sea storage of knowledge, sealed in nautilus chambers.',
    icon: '🧠',
    positionX: 330,
    positionY: 30,
    width: 70,
    height: 70,
  },
  {
    id: 'skill-forge',
    name: 'Hydrothermal Forge',
    description: 'Craft skills in volcanic vents from the ClawHub marketplace.',
    icon: '🌋',
    positionX: 50,
    positionY: 170,
    width: 70,
    height: 70,
  },
  {
    id: 'channel-bridge',
    name: 'Coral Bridge',
    description: 'A living coral bridge connecting reef networks across the sea.',
    icon: '🪸',
    positionX: 280,
    positionY: 140,
    width: 90,
    height: 90,
  },
  {
    id: 'tool-workshop',
    name: 'Salvage Workshop',
    description: 'Build and test tools from shipwreck salvage and sea glass.',
    icon: '⚓',
    positionX: 400,
    positionY: 160,
    width: 80,
    height: 70,
  },
  {
    id: 'canvas-studio',
    name: 'Biolume Studio',
    description: 'Paint with bioluminescent ink on the ocean canvas.',
    icon: '🎨',
    positionX: 620,
    positionY: 80,
    width: 80,
    height: 80,
  },
  {
    id: 'voice-tower',
    name: 'Echo Spire',
    description: 'Sonar and whale-song integration — let your agents be heard.',
    icon: '🐋',
    positionX: 40,
    positionY: 310,
    width: 80,
    height: 70,
  },
  {
    id: 'security-fortress',
    name: 'Shell Fortress',
    description: 'Armored shell defense — permissions and reef access control.',
    icon: '🛡️',
    positionX: 180,
    positionY: 340,
    width: 70,
    height: 70,
  },
  {
    id: 'config-citadel',
    name: 'Nautilus Citadel',
    description: 'Configuration spirals — the nerve center of your reef agent.',
    icon: '🐙',
    positionX: 490,
    positionY: 300,
    width: 70,
    height: 70,
  },
];

export const LOCATION_IDS = MAP_LOCATIONS.map((l) => l.id);
