import type { MapLocation } from '../types/location';

// Building zones calibrated for the sea-floor map (780x468 actual dimensions)
// 10 OpenClaw integration-themed sea landmarks
export const MAP_LOCATIONS: MapLocation[] = [
  {
    id: 'cron-hub',
    name: 'Tide Clock Grotto',
    description: 'Learn automation, cron jobs, task queues, and workflow orchestration.',
    icon: '🐚',
    positionX: 80,
    positionY: 60,
    width: 80,
    height: 80,
  },
  {
    id: 'webhook-gateway',
    name: 'Current Gateway',
    description: 'Master REST APIs, GraphQL, webhooks, OAuth, and integrations.',
    icon: '🌊',
    positionX: 200,
    positionY: 50,
    width: 70,
    height: 70,
  },
  {
    id: 'memory-vault',
    name: 'Abyssal Vault',
    description: 'Study RAG pipelines, vector databases, embeddings, and context management.',
    icon: '🧠',
    positionX: 330,
    positionY: 30,
    width: 70,
    height: 70,
  },
  {
    id: 'skill-forge',
    name: 'Hydrothermal Forge',
    description: 'Practice code generation, debugging, testing, and git workflows.',
    icon: '🌋',
    positionX: 50,
    positionY: 170,
    width: 70,
    height: 70,
  },
  {
    id: 'channel-bridge',
    name: 'Coral Bridge',
    description: 'Connect via Slack, Discord, Telegram, email, and multi-channel messaging.',
    icon: '🪸',
    positionX: 280,
    positionY: 140,
    width: 90,
    height: 90,
  },
  {
    id: 'tool-workshop',
    name: 'Salvage Workshop',
    description: 'Build function calling, MCP servers, tool chains, and agentic loops.',
    icon: '⚓',
    positionX: 400,
    positionY: 160,
    width: 80,
    height: 70,
  },
  {
    id: 'canvas-studio',
    name: 'Biolume Studio',
    description: 'Query SQL, build data pipelines, scrape the web, and process analytics.',
    icon: '🎨',
    positionX: 620,
    positionY: 80,
    width: 80,
    height: 80,
  },
  {
    id: 'voice-tower',
    name: 'Echo Spire',
    description: 'Search the web, verify facts, summarize documents, and run research.',
    icon: '🐋',
    positionX: 40,
    positionY: 310,
    width: 80,
    height: 70,
  },
  {
    id: 'security-fortress',
    name: 'Shell Fortress',
    description: 'Explore Solana, wallets, DeFi protocols, and smart contracts.',
    icon: '🛡️',
    positionX: 180,
    positionY: 340,
    width: 70,
    height: 70,
  },
  {
    id: 'config-citadel',
    name: 'Nautilus Citadel',
    description: 'Manage projects, invoices, documents, scheduling, and deployments.',
    icon: '🐙',
    positionX: 490,
    positionY: 300,
    width: 70,
    height: 70,
  },
];

export const LOCATION_IDS = MAP_LOCATIONS.map((l) => l.id);
