import type { MapLocation } from '../types/location';

// Building zones calibrated for the neopia-central-map.png (780x468 actual dimensions)
// 10 OpenClaw integration-themed landmarks
export const MAP_LOCATIONS: MapLocation[] = [
  {
    id: 'cron-hub',
    name: 'Cron Hub',
    description: 'Tick-tock — schedule tasks and automate your agent workflows.',
    icon: '⏰',
    positionX: 80,
    positionY: 60,
    width: 80,
    height: 80,
  },
  {
    id: 'webhook-gateway',
    name: 'Webhook Gateway',
    description: 'Incoming signals arrive here — HTTP endpoints for the world.',
    icon: '🔗',
    positionX: 200,
    positionY: 50,
    width: 70,
    height: 70,
  },
  {
    id: 'memory-vault',
    name: 'Memory Vault',
    description: 'Deep storage of knowledge, powered by LanceDB vectors.',
    icon: '🧠',
    positionX: 330,
    positionY: 30,
    width: 70,
    height: 70,
  },
  {
    id: 'skill-forge',
    name: 'Skill Forge',
    description: 'Craft and discover skills from the ClawHub marketplace.',
    icon: '🔨',
    positionX: 50,
    positionY: 170,
    width: 70,
    height: 70,
  },
  {
    id: 'channel-bridge',
    name: 'Channel Bridge',
    description: 'A bridge connecting Discord, Telegram, Twitter, and beyond.',
    icon: '🌉',
    positionX: 280,
    positionY: 140,
    width: 90,
    height: 90,
  },
  {
    id: 'tool-workshop',
    name: 'Tool Workshop',
    description: 'Build and test custom tools and plugins for your agents.',
    icon: '🛠️',
    positionX: 400,
    positionY: 160,
    width: 80,
    height: 70,
  },
  {
    id: 'canvas-studio',
    name: 'Canvas Studio',
    description: 'Visualize data and render live canvases for your agents.',
    icon: '🎨',
    positionX: 620,
    positionY: 80,
    width: 80,
    height: 80,
  },
  {
    id: 'voice-tower',
    name: 'Voice Tower',
    description: 'Voice and speech integration — let your agents speak and listen.',
    icon: '🗼',
    positionX: 40,
    positionY: 310,
    width: 80,
    height: 70,
  },
  {
    id: 'security-fortress',
    name: 'Security Fortress',
    description: 'Permissions, access control, and security policies enforced here.',
    icon: '🏰',
    positionX: 180,
    positionY: 340,
    width: 70,
    height: 70,
  },
  {
    id: 'config-citadel',
    name: 'Config Citadel',
    description: 'Configuration and deployment — the nerve center of your agent.',
    icon: '⚙️',
    positionX: 490,
    positionY: 300,
    width: 70,
    height: 70,
  },
];

export const LOCATION_IDS = MAP_LOCATIONS.map((l) => l.id);
