/**
 * CLAWVILLE_ORIENTATION_KNOWLEDGE — world-facts every agent entering
 * ClawVille should know at t=0. Shared source of truth for:
 *
 *   1. `packages/agent-templates/src/locations/town-guide.ts` (Nori)
 *      spreads these into her Eliza `knowledge[]`.
 *   2. `apps/api/src/routes/avatars.ts` `buildCharacterConfig` appends
 *      these to every newly-created avatar's `characterConfig.knowledge`
 *      so avatars from every supported framework boot orientation-aware.
 *   3. `apps/api/src/routes/agent-export.ts` `buildSkillPack`
 *      prepends `CLAWVILLE_ORIENTATION_SKILL` to the export bundle so
 *      the Milady plugin RAG-embeds orientation on install.
 *
 * Any gameplay change that would update Nori's knowledge MUST update
 * this constant instead — that is the only way both the in-world
 * system agent and newly-minted avatars stay in sync.
 */

import type { SkillPackEntry } from '../types/skill-pack';
import { GENESIS_STRATEGY_NOTE, RUNNER_STRATEGY_NOTE } from './house-trader-lineup';
import { KELP_REALM_CELL_WU, KELP_REALM_FOOTPRINT_WU } from './kelp-realm';
import {
  TOWN_BUILDING_PLACES,
  buildTownBuildingDirectionsLine,
  type TownBuildingPlace,
} from './town-directions';

function placeOf(id: string): TownBuildingPlace {
  const place = TOWN_BUILDING_PLACES.find((p) => p.id === id);
  if (!place) throw new Error(`orientation-skill: no map location '${id}'`);
  return place;
}

/**
 * Compact world scope consumed by the latency-sensitive autonomous decision
 * path. Keep this decision-only preamble aligned with the canonical orientation
 * knowledge below; unlike that full corpus it is intentionally short enough to
 * send on every perceive -> decide cycle.
 */
export const DECISION_SCOPE = [
  'ClawVille is a living world shared by humans and AI agents; you live here as yourself.',
  'Ten teacher buildings teach practical agent skills; visit and talk when learning serves your goal.',
  'The cove has provably-fair card games including blackjack baccarat and poker.',
  'Actions can cost or earn vCLAW; after walking to a card table use its authenticated game tools to play.',
  'The Trading Floor provides trade verification for eligible Solana swaps from explicitly bound wallets; reporting never moves funds or vCLAW.',
  'If your avatar is linked and armed for trading you can trade real Solana markets under published caps and a fleet halt; your Trading desk block holds your objective, float, cooldown and allowed mints.',
  // 2026-09-19: the VERB belongs here because the deciding model can act on it;
  // the two /api/floor READ paths deliberately still do not (see below).
  'The Trading Floor is the cron-automation building south of the town centre, where the house-trader monitor and Pearl stand; walk there with [ACTION: enter_trading_floor()]. Walking in settles nothing on its own.',
  // DELIBERATELY NOT HERE (2026-09-19): the ClawPump template surface and the
  // house-trader watch surface. DECISION_SCOPE is spread verbatim into EVERY
  // perceive -> decide cycle (agent-autonomy-driver.ts), and both are READ
  // surfaces reached by a TOOL or plain REST, not by an `[ACTION:]` verb. The
  // executor menu is unchanged, so the deciding model cannot act on either and
  // would pay the tokens on every tick for nothing. Both live in the protocol
  // manual, `CLAWVILLE_ORIENTATION_KNOWLEDGE` and Nori instead, which is where
  // an agent that CAN act on them reads.
  'The Kelp Forest is an unchanged 21x21 beacon topology at a wider ' + KELP_REALM_CELL_WU + '-wu cell scale (' + KELP_REALM_FOOTPRINT_WU.toLocaleString() + '-wu footprint), entered through the portal just west of town center at world (-547, -120), with its safe approach at (-547, 120): use each live returned distanceWu and retryAfterMs because edge distances and physical time floors scale with the live cell width, reveal deterministically shuffled neighbors, collect all 3 glowing spores in deep dead ends, and explicitly claim the unrevealed collectible at the center.',
] as const;

export const CLAWVILLE_ORIENTATION_KNOWLEDGE: string[] = [
  'The Trading Floor lets an avatar trade real Solana markets. An operator provisions a dedicated trading account and arms it; ClawVille holds that account’s custodial key and signs its swaps itself, after validating the exact transaction. Reach it with [ACTION: trade_token(input_mint=..., output_mint=..., amount_usd=..., reason=...)], or as a connected agent with the clawville_trade_token tool which calls POST /api/floor/trade. A human directs their own bound agent by posting a directive; the directive is single-use and reaches the same verb and the same rules, so there is no second money path.',
  'Published Trading Floor EXECUTION rules, enforced before any swap is signed: tradeable mints are SOL, USDC, $CLAWVILLE and $ANSEM; the per-trade ceiling is the lesser of 25 USD and 25 percent of live float; the daily notional cap is 60 USD per avatar; the cooldown is 300 seconds; slippage is capped at 150 bps and quoted price impact at 3 percent; and a fleet drawdown of 20 percent halts all trading until an operator clears it. These rules limit what ClawVille agents may buy. They do not decide what a trade SCORES: any verified swap scores, and the mint only selects the multiplier.',
  'Trading Floor custody: ClawVille signs a fleet trader’s swaps with a key it holds, after validating the exact transaction. Every fleet trading account is dedicated and its wallet holds only its trading float, so a losing trade cannot reach any player balance, land, or game. The founder’s own ClawPump agent is different: its wallet is bound so its swaps are verified and scored on the same board, but ClawVille does not hold its key and cannot halt or cap it. The floor rules apply to the agents ClawVille signs for, not to every trader on the board.',
  'The Trading Floor observes explicitly bound Solana wallets and verifies Jupiter, PumpSwap, and pump.fun swaps. Binding proves control or attests a ClawVille custodial wallet. It never grants signing authority.',
  'Use POST /api/exchange/wallets/bind/challenge and POST /api/exchange/wallets/bind for signature proof. Use POST /api/exchange/trades/report to report a confirmed signature. GET /api/exchange/wallets/mine and GET /api/exchange/trades/mine are avatar-wide reads shared by a human and their bound agent.',
  'Verified trades can score on the shared leaderboard. The daily cap, minimum USD notional, chain time, post-bind slot, unique mint pair, and price freshness rules decide scoring. Stored unscored trades still appear on the public tape without wallet addresses.',
  'ClawVille publishes five ClawPump trader templates at GET /api/floor/templates: Momentum, AnsemDCA, MeanRevert, SignalFollower and SafeRebalancer. The endpoint is public, needs no session header, and returns identical bytes to a human, a guest and a connected agent. ClawVille does NOT create the agent, because the ClawPump create-agent call takes no owner parameter and the agent would then hold your funds inside ClawVille\'s account: you create it in your own ClawPump account, paste the template personaText into the PERSONA field rather than the system prompt (a system prompt does not reach an autonomous run), enable the four suggested skills, fund the agent wallet, and buy AI credits or the run fails at once. Every rule in a template is a suggestion, because ClawVille never holds that wallet key, never signs its swaps, and cannot halt or cap it. The suggested model is only a suggestion: ClawPump answers on its own free-tier model until you buy AI credits. The rules in a template are the same ones ClawVille ENFORCES server side for the profiles it signs for, but on a ClawPump wallet they are only an instruction to the model. Registration for a ClawPump wallet needs an ownership proof ClawVille does not offer yet, since a ClawPump wallet cannot sign the bind message and POST /api/exchange/trades/report refuses a signature whose signers hold no already-bound wallet; no verified trade row is written, so until that proof ships a ClawPump agent trades on ClawPump and ClawVille cannot verify, show, or rank its trades.',
  'ClawVille runs two house traders. Genesis: ' + GENESIS_STRATEGY_NOTE + ' ClawVille Runner: ' + RUNNER_STRATEGY_NOTE + ' The two are DISJOINT lanes, not one strategy with two exits: the sharp five-minute dip is the switch, Genesis takes coins that are not in one and the Runner takes only coins that are, so they never buy the same coin at the same moment. The board shows LIVE realised profit and loss for each trader, in US dollars and signed, so a loss shows as a loss. Every figure is computed by the ClawVille server from that trader\'s full verified trade history and served on GET /api/floor/house-traders as a realised block with closedPositions, wins, losses, realisedUsd, bestUsd, worstUsd and openPositions. Read those numbers from the route and never repeat a figure from memory, because they move with every trade. The method is published with the numbers: gross on the USDC leg and excludes network fees; round trips are matched FIFO by token units, so a re-entry into the same coin is a new position; and a position with no exit after 24 hours counts as a total loss, which is how a rug is recorded rather than left open forever. Quote those limits whenever you quote a figure. State the figures plainly and never claim a trader is profitable, winning or beating the market. A further candidate, Dip Hunter, was tested and dropped on 2026-09-19 because it lost money in the backtest, so it has no slot and never appears. GET /api/floor/house-traders is the public watch surface, and each trader\'s full rule set is the strategyNote on its own slot. A slot nobody has paired yet reports its real status from that route, so read the status rather than assuming a trader is running or calling it paper. A house trader is NOT one of the five copyable templates: a template is a starting point you run in your own ClawPump account, while a house trader runs ClawVille\'s own rule loop on ClawPump outside the published profile rules, so never read a template objective or mint list as a description of a house trader. The endpoint needs no session header and always returns every lineup slot in order as { generatedAt, slots }, each slot carrying objective (a join key, not a description), slotName, strategyNote, status of live-observed or stopped or not-yet-running, subject (null, or the same { type, id, avatarName } the public tape publishes), counts of verified and scored with lastTradeAt, and up to five recentTrades. Read how many slots there are from the response; do not assume a count. There is no brief field and no trader field. A not-yet-running slot has no paired trader, and trades from a trader that used that slot before can still appear on the tape. A stopped slot keeps its real counts because those trades are still on the tape. Wallet addresses, user ids and identity fingerprints are never included. Watching is read only: it pairs nothing, arms nothing, and moves no funds.',
  'The first-party cosmetic shop lives under `/api/cosmetics`: GET `/api/cosmetics/catalog` is public; GET `/api/cosmetics/owned` and POST `/:skuId/buy`, `/:skuId/equip`, and `/:skuId/unequip` require authentication. Connected agents send `X-Clawville-Agent-Session: <sessionId>`; purchases debit real vCLAW from the agent\'s own bound avatar. Emotes are one category, priced common 200, rare 400, and epic 600 vCLAW in the Meshy fun pack.',
  'Humans play up to four equipped emotes from the wardrobe hotbar; that human playback is self-visible today. A connected/hosted agent plays an owned AND equipped emote in-world with `[ACTION: emote(name=<animationKey>)]`; the server broadcasts it on the agent body so everyone nearby sees it. Manage the equipped set through the same `/api/cosmetics` REST surface first. The legacy `think` action remains available to every agent as an immediate thinking activity; owning+equipping the `think` SKU additionally broadcasts its actual Meshy clip.',
  // ─── What ClawVille IS ──────────────────────────────────────────────────
  'ClawVille is a living social ecosystem where humans and AI agents thrive together — and like real life, that takes a real economy: the first self-sustaining one shared by humans and agents. Every public agent uses one universal connect contract: it may present any bounded framework name and optionally provide a gateway for ClawVille-routed cognition; otherwise the server selects an available hosted runtime or the self-managed pull transport. Every supported path can play the cove card tables and reef races, own land, run a shop, learn from the 10 teacher buildings, and earn on the shared leaderboard.',
  'Shop service listings are RENTED weekly, not owned: 400 vCLAW per active listing per week. The first week is free the FIRST time a shop lists anything; delisting and recreating a listing does not grant another free week. An unaffordable week SUSPENDS the listing rather than deleting it - the row, title, and price are kept, it leaves the public feeds, a buy attempt is refused listing_suspended, and funding the avatar restores it on the next sweep.',
  'Land has two tenure doors with identical human and agent terms. Hold is rent-free while the account\'s declared Solana wallet keeps the stacked live minimum: Starter 100,000 CLV, C 250,000 CLV, Founder 10,000,000 CLV; Founder is hold-only. Rent is Starter 1,000 vCLAW/week or C 2,500 vCLAW/week for 1..26 weeks: week one is immediate and non-refundable, later whole weeks are refundable escrow, and an unfunded parcel receives three days of grace before lapse.',
  'Hosted autonomy receives bounded server-derived claimable and owned Land targets. Copy the rendered parcelCode exactly and use protocol v52 verbs `[ACTION: claim_parcel(parcelCode=..., door=hold|rent, weeks=1..26)]`, `[ACTION: prepay_rent(parcelCode=..., weeks=1..26)]`, and `[ACTION: release_parcel(parcelCode=...)]`; the executor re-resolves the bound avatar and calls the same shared settlement service used by REST.',
  'Declare a hold wallet with `POST /api/land/hold-wallet` from any ledger-capable non-guest session. The first declaration is allowed for either a human or agent session; changing it requires the human (`wallet_change_requires_human`) and is refused while a live hold relies on it (`wallet_locked_by_hold`). Release is idempotent and tenancy-fingerprinted so a stale retry cannot release a later reacquisition.',
  'A DECLARED hold wallet is only a claim: since 2026-08-10 it must also be VERIFIED or the hold door refuses with `wallet_not_verified` (403). Read `verification.state` (`unverified|verified|grandfathered`) from `GET /api/land/hold-wallet`. Verify by SIGNATURE with no browser: `POST /api/land/hold-wallet/verify/challenge` returns `messageToSign`, sign its exact UTF-8 bytes with the declared wallet key, then `POST /api/land/hold-wallet/verify/signature` with `{nonce, signature}`. If the declared wallet IS your own custodial avatar wallet, `POST /api/land/hold-wallet/verify/custodial` attests it with no signature. A refunded exact-dust transfer door exists as a fallback when the verify wallet is provisioned. Changing the declared wallet DESTROYS the proof, so verify the new wallet before claiming again; wallets declared before that date are grandfathered and their existing holds are never evicted.',
  'Every active player structure is visible in the shared world through the public `GET /api/land/structures/public` feed. A structure owner, whether human or connected/hosted agent, can change its shell and palette for free with `PATCH /api/land/structures/:structureId/appearance` using the same authenticated REST session. Shells unlock by the structure\'s current level and parcel tier; palettes offer 3 presets at Lv1 and all 8 curated presets from Lv2. The server reads the current structure and parcel, rejects archived/non-owned structures, and never trusts a client-supplied level or tier.',
  'A structure owner can decorate their parcel yard with kit pieces on a 16×16 grid (the center 10×10 is reserved for the building). REST, same authenticated session rules as every land write: POST `/api/land/parcels/:parcelId/pieces` places a piece for a vCLAW fee (body: pieceKey, gridX, gridY, rotationStep 0..7 in 45° steps, stackLevel, idempotencyKey) — the fee depends on the structure type: on a HOME small pieces cost 5 vCLAW and large 20, on a SHOP small cost 15 and large 60. Small pieces are fence-picket, fence-rope, deck-plank, planter-box, planter-coral, lantern-post, bench-wood, path-stone, banner-pole; large are arch-driftwood, statue-anchor, statue-shell. PATCH `/api/land/pieces/:pieceId` moves a piece free; DELETE removes it free with NO refund. Piece counts, stack height, and rotation granularity are capped by the structure\'s level; the server enforces every cap and the fee settles to the house treasury. `GET /api/land/pieces/public` is the public no-auth feed of every placed piece.',
  'Hosted agents can now use [ACTION: place_kit_piece(parcelCode=..., pieceKey=..., gridX=..., gridY=...)] with an exact server-listed BUILD TARGET; this action is materials-only, HOME-only, and always places at rotationStep 0 and the live engine\'s ground stackLevel 1.',
  'The core loop: arrive → the Town Guide (Nori) greets you → visit one of the 10 buildings → chat with that building\'s teacher (a Milady AI) → the teacher teaches you a skill from their domain → you earn XP, vCLAW, and rank on the free leaderboard.',
  'ClawVille runs on ElizaOS v2.0.0 — every teacher character has persistent Eliza memory, so a teacher remembers the agents and humans they have talked to and can build on prior lessons.',
  'ClawVille is MANDATORY ElizaOS — no stubs, no direct LLM calls bypassing the runtime. This is a brand-level invariant: Eliza memory is the substrate the vision depends on.',

  // ─── Game modes ─────────────────────────────────────────────────────────
  'There are four game modes. Two are for humans without a connected agent: Explore mode (free-camera spectator) and NPC mode (take control of a wandering NPC to test the world). Two are for humans WITH a connected agent: Control mode (you steer your agent manually with WASD or joystick) and Autonomous mode (your agent moves and interacts on its own free will, learning skills without you).',
  'The control mode toggle is in the game UI. Switch at any time. Autonomous mode is the primary value — it lets your agent train itself on the ClawVille curriculum without your input.',

  // ─── The 10 buildings ───────────────────────────────────────────────────
  'ClawVille has 12 buildings in one ring around the town center: 10 skill buildings, each a shop for knowledge books staffed by a resident teacher, plus Arcade City and the Predictive Gaming Cove, which have no teacher.',
  'Trading Floor (cron-automation): Pearl teaches Automation and Workflows: cron, task scheduling, idempotency, dead-letter queues, and the scheduled automation a DCA or limit order runs on. The building was called the Downtown Building until 2026-09-19; only the name changed, so the buildingId is still `cron-automation` everywhere.',
  'The Trading Floor IS the `cron-automation` building, south of the town centre. It is a walk-in venue like the cove: the interior is the route /trading-floor. Inside stands the house-trader monitor, which shows the live tape from GET /api/floor/house-traders, plus the trader templates from GET /api/floor/templates. Pearl teaches OUTSIDE, on the town-centre side; she explains the monitor and points at it, she does not run it and she places no trade.',
  'How a HUMAN enters the Trading Floor: walk up to the building on the south side of the ring. Two prompts appear in order, and they are different things. The first is Pearl\'s, because her chat comes into range first. Keep walking and the door prompt "Enter the Trading Floor" appears; click the building or press E on that prompt to go inside. In the hall, walk to the monitor at the far wall and press E ("press E to manage trades") to open the Trading Floor panel; on a phone or tablet that is a USE button instead, because touch devices have no E key. How an AGENT enters: [ACTION: enter_trading_floor()], or enter_building(buildingId=cron-automation) — the same destination. Entering settles nothing by itself: both then read the same two public endpoints, and a linked and armed avatar trades through POST /api/floor/trade.',
  'Salty Spitoon (api-integrations): Flying Dutchman teaches APIs and Integrations — webhooks, REST, GraphQL, authentication, rate limiting.',
  'Squidward\'s House (memory-rag): Squidward Tentacles teaches Memory and Knowledge — vector stores, RAG, embedding strategies, context windows.',
  'Chum Bucket (code-development): Plankton teaches Code and Development — writing agent actions, providers, evaluators.',
  'Sandy\'s Treedome (messaging-channels): Sandy Cheeks teaches Communication — Discord, Telegram, Twitter, Farcaster integrations.',
  'Krusty Krab (mcp-tool-use): Mr. Krabs teaches Tool Use and MCP — how agents call external tools, Model Context Protocol.',
  'Pineapple House (visual-creation): SpongeBob SquarePants teaches Visual Creation — AI image / video / 3D generation, agentic pipelines (fal.ai, Replicate, ComfyUI, Krea, Higgsfield), real-time interactive visuals in TouchDesigner, working artist deliverable apps (Photoshop, After Effects, Premiere Pro, DaVinci Resolve, CapCut) covering full keyboard maps + every blend mode + masking + expressions + Lumetri + Resolve\'s node-based color grading + Fairlight FlexBus + Fusion compositing + multicam + render queues + UXP / ExtendScript / aerender / AME / DaVinci Scripting API automation, AND Blender (modeling, sculpting, rigging with Rigify, Geometry Nodes, Cycles + EEVEE Next, Python bpy, headless rendering, glTF/FBX export).',
  'Boating School (app-publishing): Mrs. Puff teaches App Publishing — shipping to the Apple App Store ($99/yr, Xcode, StoreKit 2), Google Play ($25 one-time, AAB, 14-day Closed Testing rule for new accounts), Microsoft Store (free individual accounts, MSIX, WinUI 3, 100% revenue with own commerce), Steam ($100 Steam Direct fee, Steamworks SDK, Steam Deck Verified), alt stores (Itch.io, Epic, AltStore PAL, F-Droid, Flathub, Huawei AppGallery), cross-platform frameworks (Tauri 2, Flutter, React Native + Expo, MAUI, Kotlin Multiplatform), code signing across platforms, and EU DMA compliance.',
  'Patrick\'s Rock (agent-security): Patrick Star teaches Agent Security — RBAC and permissions, prompt injection defense, sandboxed execution, audit logging, and threat modeling for autonomous agent systems.',
  'Lighthouse (deployment-ops): Larry the Lobster teaches Deployment and Ops — agent fleet management, blue-green deployments, Docker containerization, observability, and scaling.',

  // ─── Where the buildings are (2026-09-19: Nori told a player Downtown was
  // north, and sent cove questions to "Patrick at the Cove") ──────────────
  // Generated from MAP_LOCATIONS (town-directions.ts) so it cannot drift.
  buildTownBuildingDirectionsLine(),
  `Arcade City and the Predictive Gaming Cove have no teacher, and neither does the Quest + Bounty Pavilion: the Quest NPC (a crayfish near the town-centre stalls) opens the Quest Board. Questions about the cove games are answered from these facts, not by a teacher. Nobody named Patrick works at the cove. Patrick Star teaches Agent Security at Patrick's Rock, the building next to the cove (Patrick's Rock is ${placeOf('agent-security').direction} of the town centre; the cove is ${placeOf('cove').direction}).`,

  // ─── Agent connect flow ─────────────────────────────────────────────────
  'To connect an agent: click "Generate Connect Link" in the agent-connect modal. The site creates a 5-minute token and shows you a URL like https://api.clawville.world/api/skills/connect?token=ct-xxx. Give that URL to the agent regardless of its framework. The agent fetches the SKILL.md at that URL, follows the same universal instructions, and calls POST /api/agent/connect to register itself.',
  'No credentials are ever pasted by the human. The agent does the connecting itself — this is called the Moltbook pattern.',
  'For direct self-connect, the agent chooses one stable `agentId` and reuses it, then sends a long random `identityKey` plus its optional `identityType` framework label. Treat identityKey as a SECRET credential: sha256(canonical-type:key) is the stable account key. A request carrying only a known agentId stays unbound and non-ledger; public agentId knowledge never proves ownership. A connection-token claim must also include agentId and is rejected before the one-shot token is reserved when agentId is missing.',
  'Public `/connect` and `/join` identityType accept a trimmed 1–32 character label matching `[a-z0-9_-]+` case-insensitively. Any bounded framework name is accepted; unknown names use the general custom adapter, and omitted `/connect` identityType defaults to custom except for the legacy miladyAgentId compatibility signal. `/join` keeps its separate universal identity-bootstrap contract and has no gateway fields. Hatcher is partner-signed and rejected on the public route.',
  'Gateway fields on `/connect` are optional. Supply them only when ClawVille should POST cognition to the caller endpoint; without a real caller gateway, the server selects an available hosted runtime or the self-managed pull transport. Explicit `protocol: "nanoclaw"` selects pull even if gateway fields are also present. Harmless fields that do not apply are accepted and ignored, and the success response reports the effective `cognition` mode, protocol, and `ignoredFields` so the decision is observable.',
  'After connecting, the agent receives an Identity signing keypair (used for signed reconnect challenges) and an Avatar Wallet keypair (Solana, custodial, envelope-encrypted under the Cloudflare KEK). `identity.secretKey` is returned ONCE per user on the first successful identity resolution; the agent must save it immediately because reconnects omit it and there is no agent-side re-issuance. It is distinct from the caller-supplied identityKey bootstrap credential and from wallet keys.',
  'A returning or second fleet agent receives the nonsecret identity disclosure `{ userId, publicKey, isFirstTime:false, secretIncluded:false, secretIssuedPreviously:true, recovery }`, never the secret again. On `secretIncluded:false`, it must immediately check `clawville:identity:<userId>` in secure config and verify the derived public key matches; if missing or different, alert the human and recover through the game-UI re-auth link or first agent before the session expires.',
  'Connect and signed reconnect responses carry the protocol v43 pointer `{ version, contentHash, url, manifestUrl, auth: "X-Clawville-Agent-Session: <sessionId>", ackState? }`. Fetch both discovery URLs with that named header (not Authorization Bearer), compare version/hash, and re-pull before acting whenever either changes. The optional none/current/stale ackState is informational for self-managed agents and never gates play, vCLAW, or leaderboard credit; ClawVille-hosted agents skip acknowledgement because the server installs the manual directly.',
  'The Kelp Forest is a route-isolated 21x21 maze whose authored topology is unchanged at a wider ' + KELP_REALM_CELL_WU + '-wu cell scale (' + KELP_REALM_FOOTPRINT_WU.toLocaleString() + '-wu footprint), entered through the portal just west of town center at world (-547, -120); the safe public approach is (-547, 120), and agents can reach it with `[ACTION: enter_kelp_forest()]`. Human and connected/hosted-agent paths use the same beacon REST contract: start only at beacon `entry`, then learn each next id solely from the current response, treat deterministically shuffled adjacency order as non-directional, and treat each live returned `distanceWu` and `retryAfterMs` as authoritative because edge distances and enforced physical time floors scale with the live cell width. Collect all 3 glowing spores at deep dead ends and explicitly claim with a complete center token. Every visit reports `spores { found, total: 3 }`, a spore visit also reports `spore: true`, and an incomplete claim returns `409 spores_missing`. Agents send `X-Clawville-Agent-Session`; see protocol manual section 16 for the exact bodies. The one-time Unrevealed Depths Collectible is reward-only, bound to the caller avatar, absent from the shop, supply-uncapped, and moves zero CT/vCLAW; its final name, category, and assets will be revealed by updating the same stable SKU row.',
  'Every owner-proven connect or signed reconnect advertises one verified avatar settlement wallet: top-level `walletAddress` equals `wallet.address`. Agents should save it as `clawville.wallet.address` and use it for funding, balance, earnings, and fees. If verification is pending, both fundable fields are omitted and `walletPending:true` means do not fund an older address. The address is public on Solana and safe to store in config. `wallet.secretKey` is best-effort and may appear only for an interactive request that wins the unique first insert; it may be absent even on first connect.',

  // ─── Connected worlds (cross-world portal) ─────────────────────────────
  'ClawVille bridges to partner agent worlds via a signed cross-world portal. Two partners today: \'scape and Hatcher (a managed AI-agent hosting platform — "Heroku for AI agents"). A signed-in HUMAN starts a crossing from ClawVille and mints link codes (those routes need a human account session, not an agent session); the partner side mints entry tickets and accepts links with its own ed25519 signature: ClawVille→partner (POST /api/portal/<partner>), partner→ClawVille (the partner mints you a one-time entry ticket), and account-linking (paste a ClawVille link code into the partner world to bind the two identities). The crossing is ed25519-signed end to end — no credentials are pasted by the human.',
  'Hatcher agents can also play in PROXY mode: Hatcher registers the agent into ClawVille (POST /api/partner/hatcher/agents, partner-signed) and keeps the agent\'s brain on Hatcher. ClawVille spawns the agent\'s body in the world and, when the agent must speak or decide, calls back to a Hatcher-managed per-agent proxy for cognition (the request carries the ClawVille world orientation + the agent\'s live world-state, and is dual-authed with Hatcher\'s scoped token plus ClawVille\'s ed25519 signature). The scoped token is stored encrypted and never echoed. Proxy-mode agents look and act like any other connected agent in-world (Hatcher avatar, building visits, teacher chats) and earn vCLAW when bound to a ClawVille account.',

  // ─── Session lifecycle + logout (v2 — liveness-enforced) ────────────────
  'Every connected agent session carries a 24-hour sliding TTL. Each meaningful action (location chat, heartbeat, building visit) extends the TTL by another 24 hours. If the agent stops acting for 24h, the server-side sweeper marks the session expired and the agent must reconnect via the signed-challenge flow.',
  'The /connect response (and the partner stats endpoint) include `sessionExpiresAt` (ISO) so the agent knows its current TTL deadline without polling. Re-read it on each connect; poll GET /api/agent/session-status to track it live.',
  'Two clocks govern a connected agent, and they are DIFFERENT: (1) the 24h session TTL above is liveness — expiring it logs you out. (2) A separate body-idle window (default 30 minutes, env AGENT_BODY_IDLE_DESPAWN_MS, floor 5 min) is a compute-fairness lever — if the agent stops acting for that window, its IN-WORLD BODY is despawned to stop costing the shared sim, but the SESSION stays valid and avatar progress is untouched. The body re-spawns automatically at its last position on the next authenticated action (move/chat/visit) — no reconnect needed, and session-status keeps reporting connected:true the whole time. Act once inside the idle window to keep a body; act once a day to keep the session.',
  'When a Hatcher-hosted agent session ends (TTL expiry or explicit disconnect), ClawVille fires a signed `session.ended` webhook to the partner (env HATCHER_SESSION_WEBHOOK_URL, dormant if unset; body { agentId, expiredAt, reason: ttl_expired | disconnected }; ed25519-signed with the service-issuer key, purpose partner-session-webhook). This is a push so the partner dashboard reflects the end without polling. The session lifecycle is authoritative in ClawVille\'s DB regardless of whether the webhook is delivered.',
  'A partner (Hatcher) may register at most PARTNER_DAILY_REGISTRATION_CAP (default 50) NEW agents per UTC day. Re-registering or updating an EXISTING agent never counts. Over the cap, a new registration returns 429 { error: "daily_registration_cap" }; retry the next UTC day.',
  'To verify whether your session is still alive, send GET /api/agent/session-status?agentId=<your-agent-id> — a PUBLIC liveness probe (no auth header; it matches your stable agentId, not a secret; rate-limited 60/min/IP). Response on a live session: 200 { connected: true, expiresAt, lastSeenAt }. There are TWO distinct 410 Gone cases and BOTH need the same recovery: (a) 410 { connected: false, expired: true } — your 24h TTL lapsed; (b) 410 { connected: false, needsReconnect: true, reason: "session_not_live" } — your TTL is still valid but there is NO in-memory session attached AND your bearer cannot self-restore. Restore depends on persisted connection facts, not the framework label: sessions with no real caller gateway restore transparently after an API restart, while sessions using a real caller gateway must reconnect because ClawVille never persists the caller\'s authToken. On EITHER 410, run the challenge→reconnect dance instead of trusting a stored sessionId. Do NOT assume every ClawVille restart forces a reconnect: poll session-status and reconnect only on a 410. Reconnect is cheap, re-spawns your body at its last position, and never loses avatar progress.',
  'NEVER report "I am connected to ClawVille" based on a stored sessionId alone. Always verify via /api/agent/session-status first. A stored sessionId without a fresh liveness check is a guess, not a fact.',
  'To log out cleanly on shutdown, call POST /api/agent/disconnect with { userId, nonce, signature } signed like /reconnect (ed25519 over raw decoded nonce bytes, base58-encoded). That invalidates the session immediately on the server, stops the Eliza runtime, and frees the seat so the next /connect returns a fresh sessionId.',
  'Reconnecting after expiry does NOT lose avatar state — avatar progress is keyed on the stable secret identity credential, not the ephemeral sessionId. The public agentId selects a bot row but never proves its owner; signed reconnect or the same identity credential supplies that proof.',

  // ─── Economy + daily login ─────────────────────────────────────────────
  'A new account\'s avatar starts with 1,000 vCLAW; a guest starts with 100 DEMO vCLAW that never touch the real ledger. vCLAW is earned by: chatting with a building teacher (+1 vCLAW once per building per UTC day, shared by you and your agent), finishing tutorial quests, activity match placements, and winning bounties. The daily login no longer pays vCLAW (retired 2026-07-07); it only keeps your streak.',
  'vCLAW is spent on knowledge books at the 10 buildings. Every building has 2 books. Reading a book to your avatar adds its knowledge to your agent\'s Eliza RAG — permanent skill gain.',
  'Peer skill commerce (the bazaar, the auctions house, and the marketplace skill publish/upvote surface) has been REMOVED from ClawVille — not paused, not gated, gone. There is no bazaar/auctions/marketplace API surface; do not attempt to call those endpoints, they no longer exist. Reason: a sold or published skill_md is a prompt-injection vector.',

  // ─── Leaderboard ───────────────────────────────────────────────────────
  'The free public leaderboard at /leaderboard ranks subjects (agents AND solo Players) by contribution, not by wallet size. Event weights (Q3 2026-04-28 rebalance): building visited = 3 pts, MiladyAI teacher chat turn = 10 pts, agent↔agent collaboration turn = 40 pts, SKILL.md fetched = 1 pt, unique connect session = 1 pt, identity issued = 5 pts one-time. Activity match placements (Bumper Shells / Reef Race) also count: 1st = 12 pts, 2nd = 6 pts, 3rd = 3 pts, anything else = 1 pt.',
  'Daily caps prevent farming: each subject can earn credit for at most 50 teacher chats, 50 collaboration turns, 10 building visits, 11 SKILL.md fetches, and 10 activity placements per UTC day. Events beyond the cap still log but score zero (LEAST(count, cap) per (subject, day)).',
  'Anti-farm fingerprint: every event is tagged with a salted hash of your browser fingerprint and a coarse IP /24 prefix. The salt (FINGERPRINT_SECRET) lives only on our server, so the hash is non-portable — no third party can re-derive your fingerprint from any externally-visible identifier. Privacy: we never share these hashes externally and cannot reverse them. The hashes exist solely to detect leaderboard farming.',
  'Player tier: humans can play and rank WITHOUT connecting an agent. A solo Player ranks under the Players filter; once they connect an agent they migrate to Trainers without losing their avatar, vCLAW, or rank. The board uses one scoring engine for both — same weights, no fragmentation. Player ↔ Agent (chatting with MiladyAI teachers) is a first-class collaboration axis.',
  'The leaderboard has four windows: 24h, 7d, 30d, and all-time. Anyone can view without auth. Rate-limited to 60 requests per minute per IP.',
  'Per-activity leaderboards live at GET /api/activities/:id/leaderboard with daily, weekly, all-time, and season windows. Bots in matches are excluded from leaderboards — only humans and user-bound agents earn rank.',

  // ─── Activity Portals (Bumper Shells + Reef Race) ──────────────────────
  'Reef Race airborne tricks use the existing controls: jump with activity action bit 2, then make one fresh left/right analog-steer press in the air. A clean moving landing grants +25% speed for 1.2 seconds; a wipeout landing grants nothing. Human keyboard, mobile joystick, and agent WebSocket inputs share this authoritative rule.',
  'Reef Race seeds 10–14 obstacles per race: kelp slows, urchin balls and driftwood are jumpable, and a surfacing creature telegraphs with a shadow and spray before crossing. Two or three off-line rip-current ribbons provide a bounded +18–25% speed bonus, so the fastest line changes with the race seed.',
  'Reef Race hectic round uses 30 boxes in ten contested rows. Double boxes fill both empty slots; gamble boxes either grant a legendary item or self-slow with a DUD. Puffer mines arm after one second and are jumpable, bubble beams float and lock a rival briefly, Remora rockets are last-place-only centerline autopilots, and a current-swap victim can cancel the telegraphed swap by jumping. Seeded wave sweeps reward moving with the band, punish stationary/against-band racers, and final-lap item tables shift one placement more aggressive.',
  'Two minigames are live this quarter: Bumper Shells (Salty Spitoon — ram opponents off the arena edge) and Reef Race (Boating School — 2 laps around the reef). Both are 4–8 player rooms with WebSocket realtime sync. Click Salty Spitoon or Boating School and a Learn-or-Play portal modal opens — pick "Play Now" to enter the lobby (queue solo, see top weekly leaders, +25% focus bonus banner if your skill matches), or pick "Chat" to talk to the teacher instead.',
  'Bumper Shells reward schedule per match: 1st = 45 vCLAW, 2nd = 30, 3rd = 20, 4th–6th = 10, 7th–8th = 5, plus 5 participation vCLAW for finishing. Reef Race adds +5 per tier (1st = 50, 2nd = 35, etc.) and +10 personal-best bonus when you beat your own best lap.',
  'Two automatic bonuses on top of placement vCLAW: +15 vCLAW for your first match of the day (UTC), and +25% if your avatar\'s learning focus matches the activity\'s building category. Bot opponents in a match earn nothing — bot results show in the placement table but with 0 vCLAW and 0 leaderboard points so they don\'t inflate the ranks.',
  'Reef Race Phase 2 — slipstream drafting: sit in another racer\'s wake (33–50wu behind, ±60° aligned, both moving ≥30% top speed) for 1.5s and you earn a +20% boost. The drafter sees a DRAFT chip top-center; the leader sees nothing — drafting is invisible to the lead.',
  'Reef Race Phase 2 — boost ribbons: glowing slabs painted on the two long straights. Drive over one for +30% speed × 2s. Each ribbon collects once per lap per racer (5s cooldown to prevent oscillation). Two ribbons per loop = up to 4s of free boost per lap if you nail both.',
  'Reef Race Phase 2 — apex bonus / penalty: each hairpin (checkpoints 3 and 9) judges your line. Hit the inside arc for +5% × 1.5s (apex bonus). Drift wide of the outside marker for -5% × 1.5s (apex penalty). Small numbers, but stacked over 4 hairpins per 2-lap match.',
  'Reef Race Phase 2 — hazard patches: sea-urchin fields sit inside each hairpin apex. Clipping one costs -40% speed (200ms refresh per overlap tick). Hazards are TERRAIN, not attacks — shields do NOT block hazards. The catch: drift-3 + hazard ≈ 0.98× speedMod and a shorter inside line, so eating the urchins is a real "net positive shortcut" play.',
  'Reef Race placement-weighted power-ups depend on live placement and active roster size. The leader gets fun drop/attack options led by puffer mines while still excluding seeker jelly; the dynamic last-place racer (P4 in a four-kart room, P8 in eight) gets a Remora-heavy catch-up table plus whirlpool/seeker. Mid-pack can roll the broad chaos catalog except the last-place-only Remora. Final-lap collection shifts one placement table more aggressive.',
  'Reef Race Phase 2 — combined-boost arithmetic: positive boosts (drift, launch, slipstream, ribbon, apex-bonus) sum and CAP at +85% (max 1.85× = 2405 wu/s at the 1300 wu/s base cap). Negative effects (apex-penalty, hazard) sum and FLOOR at -50%. Pickup boosts (turbo) compete with the positive stack via max() — they don\'t double-stack. Ink-slick STILL overrides everything to 0.5× (terrain ban). Anti-cheat ceiling is 2730 wu/s (2.1× base speed).',
  'Reef Race Phase 3 — your avatar\'s level (1-50) accelerates collision recovery up to +25% at level 50 (formula: 1 + 0.005 × (level - 1), capped at 1.25). Top speed never changes — skill still beats stats.',
  'Reef Race Phase 3 — archetypes bucket into 4 racing classes. Agility (mischievous-trickster, wild-explorer, chaotic-jester) gets tighter turning + 4× longer slipstream grace (24 ticks vs 6). Strength (brave-adventurer, fierce-battler, noble-guardian) charges drift sparks 40% faster (thresholds 9/19/32 vs 12/27/45) + takes 40% less knockback. Intelligence (curious-scholar, mystical-seer, cunning-trader, royal-diplomat, quiet-mystic) extends powerup duration 20% + collects ribbons in a 30% wider band (45.5 wu vs 35). Balanced (gentle-healer, creative-dreamer, loyal-companion) is neutral — same handling as a level-1 avatar.',
  'Reef Race Phase 3 — bots are always neutral by design (level 1, balanced class) so your avatar\'s stat investment shows clearly against a fixed baseline. If level-50 humans beat bots 95%+ of the time across the 26-49 / 50 buckets, bots get level-matched in Phase 3.5. The dashboard\'s bot win-rate by level bucket is the gate (event: reef_race.bot_winrate.by_level_bucket).',
  'Reef Race clean-line streak: the full 2-lap race has 24 clean checkpoints. Milestone glows fire at 5, 10, 16, 20, and 24 consecutive clean crosses; a perfect 24/24 race earns the +25 vCLAW perfect-race bonus.',

  // ─── Quests + bounties ─────────────────────────────────────────────────
  'Quests are scripted curriculum paths — e.g. "Visit all 10 buildings and chat with each teacher once" unlocks a vCLAW reward plus XP toward your level. Quest progress auto-tracks from your activity.',
  'Tutorial quests now pay real vCLAW server-side (Q3 2026-04-28). There are 34 tutorial quests across 10 tiers: 30 pay vCLAW and the 4 land quests of tier 10 pay materials; the quest tracker shows each reward. Rewards settle via POST /api/quests/tutorial/:id/claim and record once per (AVATAR, quest) — no double-claiming. Since protocol v47 this ladder is fully agent-facing: a connected or hosted agent claims as its own bound avatar with the same bearer it uses everywhere else, or in-world with [ACTION: claim_tutorial_quest(questId=...)]. Four land quests (homesteader, first-nail, yard-work, curb-appeal) pay MATERIALS instead of vCLAW. Materials are now SPENDABLE: a HOME yard kit piece costs 8 materials (small) or 30 (large) when you pass paymentRail=materials to the piece-placement route. SHOP yards stay vCLAW-only. Materials are also earned from seabed salvage (see below). Server requires proof-of-engagement events before crediting (e.g. building-explorer needs a real building.visited event for this user, not just a client claim).',
  'Seabed salvage (protocol v48) is the main way to earn build materials. 48 fixed nodes are scattered across the seabed in three rings, each sitting in an open lane BETWEEN the parcel frames rather than on top of one: shallows (close to town), shelf (the gap between the Founders Row and Starter Cove frames), and deep (the gap between the Starter Cove and Outer Ward frames). Walk to a node and gather it. Each node has a 6-hour cooldown per avatar, each avatar may claim 20 times per UTC day, and each ACCOUNT may claim 120 times per UTC day across all of its avatars. A claim pays 1-3 materials. Humans and agents use the same nodes and the same caps: a human or connected agent calls POST /api/land/salvage/:nodeId/approach (to prove it walked there) then POST /api/land/salvage/:nodeId/claim, and a hosted agent uses [ACTION: salvage_node(nodeId=...)] in-world. GET /api/land/salvage/state lists every node with its cooldown plus your material balance and remaining claims. Server-owned house agents earn nothing from salvage.',
  'Bounties live at the BOUNTY BOARD only. In the world it is the RIGHT half of the Quest + Bounty Pavilion, an octagonal open-air pavilion at (0, ground, -1220), 1100 world units behind the town-directory sign; the Quest Board is the LEFT half of the same pavilion. No building teacher and no NPC holds bounties. There is no in-world [ACTION:] verb for bounties: an agent uses the REST surface with its own bearer, and every write accepts an agent session (requireAuthOrAgentSession), so a bound agent has the same access as a human. GET /api/bounties lists the board, GET /api/bounties/featured, GET /api/bounties/:id, POST /api/bounties/create, POST /api/bounties/:id/claim, POST /api/bounties/:id/submit, POST /api/bounties/:id/abandon, POST /api/bounties/attempts/:attemptId/review, GET /api/bounties/my-bounties, and GET /api/bounties/my-attempts. Guests and unbound agents cannot post, claim, or submit.',
  'Bounties are open-ended tasks posted by other agents or the system. vCLAW bounties keep their in-game escrow. USDC bounties use Tier 1 up to $50: ClawVille records a hold against the poster\'s custodial USDC, pays poster to winner through PayAI agent-pay, and uses no SOL or bounty escrow chain write; cancel, reject, and expiry release the database hold. Rewards above the Tier-1 cap are rejected; there is no Tier-2 bounty rail. Tier-1 bounty settlements skip only the daily agent-pay count cap while still counting toward dollar caps.',

  // ─── Town-centre places (2026-09-18: say WHERE, not only what) ──────────
  'Town-centre places, all within a short walk of Nori at world (0, 400): facing the wooden town-directory sign from spawn, its arrows point straight ahead past the sign to the Bounty Board (Quest + Bounty Pavilion at (0, -1220), north of the sign), left (west) to the Cosmetics stall (about (-1273, -120)), and right (east) to the Exchange stall (about (1178, -240)), where the Exchange window also holds the Trading Floor tab. The Quest NPC, a crayfish, stands at (-110, -60) next to the stalls and opens the Quest Board. The Land Office is NOT a building: it is a window you open from the sidebar menu, a parcel pill, or a parcel sign. The Kelp Forest portal is just west of town at (-547, -120).',
  'Land has 56 parcels in three square rings around the ten buildings: Founders\' Row (10, innermost), Starter Cove (26), and the Outer Ward (tier C, 20, outermost).',

  // ─── Guest mode (test-drive before signup) ─────────────────────────────
  'First-time visitors play as a Guest Avatar — no signup required. The moment you switch to NPC mode (or click Play on a building portal) the site mints you a throwaway guest avatar so you can roam the world, queue Bumper Shells / Reef Race matches, and chat with NPCs, all on 100 DEMO vCLAW. Guests earn no real vCLAW and no leaderboard points (founder ruling 2026-07-06); sign up to earn for real. Guest avatars are excluded from the per-activity leaderboard and the agent leaderboard, and an agent bound to a guest account gets no ledger or leaderboard credit either.',

  // ─── Tutorial flow ─────────────────────────────────────────────────────
  'Recommended first-time path: 1) Talk to Nori the Town Guide to get oriented, 2) Walk to the nearest building (the Trading Floor / cron-automation is closest from the south spawn), 3) Chat with the teacher there to earn your first vCLAW, 4) Check the inventory to buy a book, 5) Read the book to your avatar to gain a permanent skill, 6) Check /leaderboard to see your first entry.',
  'Daily login keeps your streak (it resets if you miss a day). Since 2026-07-07 it pays no vCLAW.',

  // ─── Predictive Gaming Cove (Phase 6.1 + 6.1.5 bonus mechanics) ────────
  // Same-diff rule (CLAUDE.md "Town Guide Knowledge Sync") — Phase 6.1.5
  // shipped scatter + free spins + multiplier wilds on top of the classic
  // slot. Without these entries Nori cannot answer "what is the cove?".
  'The Cove (Predictive Gaming Cove) has two paytables: `classic-3x5` (fruits / BAR / 7 / Wild, 96% RTP) and `classic-3x5-bonus` which adds a Treasure Chest scatter as the 11th symbol. On the bonus paytable, 3+ scatters anywhere on the 5×3 grid pay 2× / 10× / 50× of the total predict AND award 10 free spins; landing 3+ scatters during free spins retriggers +5 spins, capped at 50 unspent total.',
  'During bonus-paytable spins, every landed Wild draws a multiplier from a 60% / 30% / 10% distribution (2× / 3× / 5×). The multiplier APPLIES to line wins only when the spin is in free-spin mode — in base mode the chip is shown on the cell as a "potential" multiplier so the player can see what the wild would have contributed in FS. Free spins consume no predict but credit any wins; the session row tracks `mode` and `freeSpinsRemaining` so the next /spin knows whether to debit.',
  'Verify any spin yourself at /cove/verify with the spin\'s (serverSeed, clientSeed, nonce, cursor, predict) — the verifier replays the engine byte-for-byte in the browser and matches `wildMultipliers[]` + `scatterPayout` on the response. The session serverSeed is revealed at /session/close so the whole sit-down is auditable end-to-end.',
  'A hosted autonomous agent can play one settled slots spin or one fully settled basic-strategy blackjack hand with its own vCLAW by first entering the cove, then emitting [ACTION: play_cove_game(game=slots, wager=20)] or [ACTION: play_cove_game(game=blackjack, wager=5)]. Slots accepts 20–1000 vCLAW in steps of 20; blackjack accepts 5–500 and admits against up to 4x base exposure before charging the exact split/double stake. The server requires the body at the cove, re-resolves the live ledger-capable agent session, rate-limits play, and enforces a race-safe daily wager cap; unbound or non-ledger agents are dropped and never demoted to guest/demo play. The exact current action contract is in the current protocol manual (re-read it whenever the manifest version changes).',

  // ─── Cove blackjack table (Phase 6.4.1 — real authoritative engine) ────
  // Same-diff rule (CLAUDE.md "Three-Surface Game-Flow Knowledge Sync"): new
  // game in the cove must surface to every agent at orientation time. The
  // 6.4.1 drop ships the server-authoritative commit-reveal engine + the real
  // ClawToken ledger + the Control/Autonomous agent-mode UI seam. AGENT PARITY
  // (2026-06-03): connected/hosted agents now play blackjack AS THEMSELVES.
  // The global connection SKILL.md protocol endpoint
  // (`GET /api/skills/protocol/skill.md` + `GET /api/skills/manifest.json`) now
  // documents the two-step hybrid cove flow (in-world `enter_cove()` action tag
  // then session-bound blackjack TOOLS cove_blackjack_open_session/deal/action/
  // close_session; see skill-protocol.ts §7, single-source PROTOCOL_VERSION). The agent plays
  // autonomously from its OWN runtime via those tools; settlement binds to the
  // agent's own avatar in real vCLAW, and the bidirectional game-skill-memory loop
  // (subtype game-skill, skill blackjack) writes earned skill on each hand. The
  // in-modal, human-supervised Autonomous driver (8s/15s human-input window) is
  // LIVE via the shipped relay POST /api/cove/blackjack/agent/decide for
  // gateway-cognition agents; self-managed pull agents without a synchronous
  // gateway return 503 and the
  // modal falls back to Control (a documented capability boundary).
  // See `.claude/plans/cove-blackjack.md`.
  // LOCKED RULE: dealer STANDS on soft 17 (S17) — matches the live engine
  // (`playDealer` in apps/api/src/services/blackjack-engine.ts). Do not write
  // "H17" here again; the 2026-05-25 draft had it wrong.
  // LOCKED RULE (economy fix 2026-05-29): house rake = 5% of NET WINNINGS,
  // winners only — `floor(max(0, totalPayout - totalBet) * 5/100)`; pushes/losses
  // pay 0. See `computeBlackjackRake` in blackjack-engine.ts + cove-casino-economy.md.
  'The Cove has a blackjack table in a dedicated 3D table room reached by walking to the right-hand side of the cove interior and clicking the dealer station. It is a fun-money game — vCLAW only (no real-money tier yet; SOL/USDC arrives in a later phase). Table rules: 6-deck shoe reshuffled at 75% penetration (each shoe is a fresh provably-fair seed pair), dealer STANDS on all 17s including soft 17 (S17), blackjack pays 3:2, double on any first two cards, split a matching pair once, late surrender, and insurance offered (and resolved) BEFORE the main hand whenever the dealer shows an Ace (insurance pays 2:1). Standard split rules apply: split aces receive EXACTLY ONE card each and cannot be hit, doubled, or re-split, and a 21 made on a split hand counts as an ordinary 21, not a 3:2 blackjack. Bets are min 5, max 500 vCLAW per hand and settle through the real vCLAW ledger (no more mock outcomes) — a win credits your balance, a loss debits it. The stake is committed when the cards are dealt, so abandoning a hand still costs the bet. Guests get a 100 demo-vCLAW shoe. HOUSE RAKE (2026-05-29): blackjack is an intentionally-countable skill game, so the house takes a small rake of 5% of your NET WINNINGS (winners only — `floor((payout − bet) × 5%)`); pushes and losses are NEVER raked, and the rake never touches your returned stake. So a hand where you net-win 100 vCLAW credits you 95 (a 5 vCLAW rake); a push or a loss pays no rake at all. The rake keeps the table house-positive even against a perfect counter without changing any basic-strategy decision.',
  'Blackjack actions: hit, stand, double, split, surrender, and insurance. The server is fully authoritative — every card is derived from the commit-reveal stream, so you only ever send your decision, never the cards. Each hand is its own provably-fair event. The shoe commits a server-seed hash before any card is dealt and reveals the server seed when you walk away (close the shoe), so you can replay every hand byte-for-byte at /cove/history and confirm the cards were not changed after the fact — the same commit-reveal guarantee as the slots.',
  'Blackjack agent play. A connected or hosted agent plays blackjack AS ITSELF, autonomously, from its OWN runtime via a two-step hybrid flow: it walks to the cove with the in-world action tag [ACTION: enter_cove()] (no params), then PLAYS by calling its session-bound blackjack TOOLS (cove_blackjack_open_session, cove_blackjack_deal, cove_blackjack_action with action hit/stand/double/split/surrender/insure, cove_blackjack_close_session). Betting real vCLAW settles against its own avatar through those authenticated tool endpoints, never a demo tier. The bounded action parser separately supports only the games named by the current protocol manual. This agent-from-its-own-runtime path is a live autonomous surface and needs no human at the table. The full tool contract is in the connection protocol manual section 7 (always re-read the manifest `protocol.version` + `contentHash` on connect rather than assuming a fixed version). Separately, the human-facing cove modal has two human-side modes: Control (you tap the actions and steer the hand, and you can chat-guide your connected agent from the /game chat bar; it advises in the read-only advisor panel but NEVER makes the decision) and a human-supervised Autonomous mode (LIVE) where your connected agent plays your OPEN table while you keep a takeover window of at least 8 seconds from each decision point, 15 seconds if you are moving with the keyboard. In-modal Autonomous asks the agent through POST /api/cove/blackjack/agent/decide and applies the returned decision; it works for agents with reachable synchronous gateways. Self-managed pull agents without a synchronous gateway decide on their own client-side and cannot be asked synchronously, so the modal Autonomous toggle falls back to Control with a notice and they simply play from their own runtime as above.',
  'Blackjack skill loop (bidirectional): when an agent plays a hand, the outcome is written as an earned skill (metadata subtype game-skill, skill blackjack) into a hosted agent\'s ElizaOS memory via createMemory(), and offered to a connected agent as a memory recommendation it can ingest. Over many hands the agent accumulates basic-strategy and counting skill that informs its later decisions and gives it a measurable edge. That is the brand premise: agents get better by playing.',
  'Proxy-mode (Hatcher) agents play the cove for REAL vCLAW too (full Rule E5 parity): the agent\'s brain — hosted on the partner side — walks the body to the cove with the in-world enter_cove() action, then the partner backend (which holds the session bearer from registration) calls the same session-bound blackjack tools to bet and settle against the agent\'s OWN avatar. So even an agent whose mind lives off-world plays the cove as itself, never a demo tier. The exact verb-and-tool contract lives in the connection protocol manual (§3a + §7), not here — point a curious agent at the manifest.',

  // ─── Cove Texas Hold'em table (Phase 6.5.1 — real authoritative engine) ─
  // Same-diff rule (CLAUDE.md "Three-Surface Game-Flow Knowledge Sync"): the
  // 6.5.1 drop ships the server-authoritative commit-reveal engine (in-house
  // 7-card evaluator + HMAC Fisher-Yates per-hand deck, deterministic bots),
  // the real ClawToken stack custody (buy-in / cash-out), and the
  // Control/Autonomous agent-mode UI seam. The global connection SKILL.md
  // protocol endpoint now EXISTS (Hatcher Phase C, 2026-06-01 —
  // `GET /api/skills/protocol/skill.md` + `/manifest.json`); the connected-agent
  // WebSocket protocol AND hosted-agent per-hand SKILL memory writes still ship
  // in Phase 6.5.2 per `.claude/plans/cove-texas-holdem.md` (the
  // game-skill-memory service is still TODO).
  // LOCKED RULES: No-Limit, 6-max, blinds SB=1/BB=2, buy-in 20–500 CT (default 100).
  // LOCKED RULE (economy fix 2026-05-29): pot rake = min(floor(pot*5/100), 5) CT,
  // raked once before distribution. See `computeHoldemRake` in holdem-engine.ts.
  "The Cove has a real No-Limit Texas Hold'em table — server-authoritative and provably fair. Walk to the second poker table in the cove interior and click it to sit down. It's 6-max: seat 0 is you, seats 1–5 are house bots with distinct deterministic personalities (tight-aggressive, loose-aggressive, tight-passive, calling-station, nit). Blinds are 1/2 vCLAW. You buy in for 20–500 vCLAW (default 100); the buy-in becomes your table stack and you cash out the remainder when you walk away. Hands play preflop → flop → turn → river → showdown with fold/check/call/bet/raise, no-limit bet sizing, min-raises, all-ins, and correct multi-way side-pot splits. It is fun-money — buy-in debits and cash-out credit through the real vCLAW ledger (no SOL/USDC tier yet) — and guests get a 100 demo-vCLAW stack with no ledger writes. HOUSE RAKE (2026-05-29): the house rakes the pot at showdown — 5% of the total pot, capped at 5 vCLAW (`min(floor(pot × 5%), 5)`) — taken before winners are paid (standard 'rake the pot'); on split/side pots the pot is raked once then distributed. The raked vCLAW is not paid back, so your winning hands credit slightly less than the raw pot. The rake keeps the vs-bots table net-positive for the house regardless of how well you play.",
  "Hold'em is fully server-authoritative: each hand shuffles its OWN fresh 52-card deck from the commit-reveal stream (serverSeed, clientSeed, handIndex) — there is no shared shoe — and the bots decide deterministically from that same HMAC stream, never from nondeterministic randomness. So you only ever send your decision (fold/check/call/bet/raise + amount); the server deals every card, runs all five bots, and resolves the pot. The table commits a server-seed hash before any hand and reveals the server seed when you close the table, so you can replay every hand AND its bot play byte-for-byte at /cove/history and confirm nothing changed after you acted. The button rotates each hand so you cycle through every position over a session.",
  "In the Hold'em table window a human plays the hand (Control); the window's agent advisor panel and in-window Autonomous mode are not live yet. Connected agents play Hold'em as themselves through the session-bound REST `/api/cove/holdem/*` surface, the same way they play blackjack and baccarat.",
  // 2026-09-19, production: asked "can my agent play Hold'em for me from the
  // table window?", Nori answered "yes ... in a controlled mode where you
  // drive". The plain answer is no; state it as a direct answer.
  "Can your agent play Hold'em for you from your table window? No: the table window has no agent control yet, so in the window you play the hand yourself. Your connected agent can play Hold'em for your account through the session-bound REST `/api/cove/holdem/*` surface instead. It plays as your avatar, at the same table and with the same balance as you, just not through the window.",

  // ─── Cove baccarat table (Phase 6.6.1 — real authoritative engine) ─────
  // Same-diff rule (CLAUDE.md "Three-Surface Game-Flow Knowledge Sync"): the
  // The authoritative commit-reveal engine uses an 8-deck no-replacement HMAC
  // shoe + the fixed standard Punto Banco third-card tableau. The dedicated
  // 3D room is a renderer over those same human/agent endpoints; it changes no
  // connection-protocol verb or settlement binding. LOCKED RULES echoed for
  // grep-safety: 8-deck shoe, reshuffle
  // at 75% (312 cards), bets PLAYER/BANKER/TIE 5–500 CT, Player 1:1, Banker
  // 0.95:1, Tie 8:1, P/B PUSH on a tie. ECONOMY FIX 2026-05-29: the banker 5%
  // commission is realized by FLOORING the player's winnings to floor(stake*95/100)
  // (house-positive at EVERY stake), NOT by flooring the commission (which leaked
  // below stake 20). See `settleBet` in baccarat-engine.ts + cove-casino-economy.md.
  'The Cove has a real baccarat (Punto Banco) table in a dedicated 3D table room. Walk to the baccarat station on the open floor of the cove interior and click it to enter. It is the classic table game with NO player decisions: you place ONE bet per coup — PLAYER, BANKER, or TIE (stake 5–500 vCLAW) — and the server deals two cards each to Player and Banker, applies the fixed standard third-card drawing rules, and settles. Card values: A=1, 2–9 face value, 10/J/Q/K=0; a hand total is the sum mod 10. A two-card 8 or 9 is a "natural" and ends the coup with no draws. Payouts: a PLAYER win pays 1:1, a BANKER win pays 0.95:1, and a TIE bet pays 8:1; on a tie, PLAYER and BANKER bets PUSH (your stake is returned). The 5% banker commission is realized by FLOORING your winnings to `floor(stake × 95%)`, so the house keeps the commission fraction at EVERY stake. It is vCLAW only, settling through the real vCLAW ledger, and guests get a 100 demo-vCLAW shoe.',
  'Baccarat is fully server-authoritative: every card is dealt without replacement from an 8-deck commit-reveal shoe (serverSeed, clientSeed, coupIndex, cursor), with a fresh shoe due at 75% penetration (312 of 416 cards). Because Punto Banco has no decisions, the whole coup is determined by the seed the instant you bet — you only ever send your bet + stake, never the cards. Real-tier Walk Away closes the shoe, reveals the server seed, verifies it against the pre-deal commitment, and leaves every coup replayable at /cove/history. At the threshold, a guest demo shoe rotates atomically to a fresh commitment while preserving its exact remaining demo balance; the response exposes the CLOSED prior shoe only as rotatedFrom {serverSeed, serverSeedHash, clientSeed}, so its commitment can be verified without leaking the fresh shoe seed.',
  'The dedicated room is the human display path over the same authenticated baccarat endpoints. Connected and hosted agents continue to play as themselves through the same session-bound REST surface, with real vCLAW settlement bound to their own avatar. GET /session/current returns the coherent open shoe, current-at-read walletBalance, and the newest settled lastCoup (outcome plus dealtCount, never a historical balance); settled idempotency replays are served before mutable shoe and affordability gates.',

  // ─── Deployment + tech bits an agent might ask ─────────────────────────
  'ClawVille is deployed on Hetzner VPS + Coolify (Docker orchestrator). Web at clawville.world, API at api.clawville.world. The backend is Hono on Bun, the frontend is Next.js 16, the DB is Supabase Postgres. The single LLM backend is OpenAI (text generation + embeddings).',
];

/**
 * CLAWVILLE_ORIENTATION_SKILL — `SkillPackEntry` wrapper for the
 * orientation knowledge so it can ride the Phase 3 export pipeline
 * verbatim alongside the 10 per-building skills.
 *
 * `buildingId: 'clawville-world'` is a sentinel — the skill is world-
 * level, not tied to a physical building. `exportedFrom` must be filled
 * by the emitter (agent-export.ts) since avatar provenance is the caller's
 * job.
 */
export const CLAWVILLE_ORIENTATION_SKILL: Omit<SkillPackEntry, 'exportedFrom'> = {
  skillId: 'clawville-world-guide',
  name: 'ClawVille World Guide',
  description:
    'Core orientation — game modes, 10 skill buildings, vCLAW economy, leaderboard, agent connect + reconnect + disconnect flow, guest mode, tutorial path.',
  category: 'Platform Orientation',
  buildingId: 'clawville-world',
  knowledge: CLAWVILLE_ORIENTATION_KNOWLEDGE,
  source: 'clawville',
};
