/**
 * Cosmetics tab — catalog grid with thumbnails (or category icon fallback),
 * scope/rarity/license badges, variant + ownership counts.
 */

import { cookies } from 'next/headers';

interface DashCosmetic {
  id: string;
  slug: string;
  category: string;
  scope: string;
  displayName: string;
  description: string | null;
  rarity: string;
  priceCt: number;
  exclusiveCurrency: string | null;
  attribution: string | null;
  attributionUrl: string | null;
  licenseSpdx: string | null;
  thumbnailUrl: string | null;
  availableUntil: string | null;
  supplyCap: number | null;
  variantCount: number;
  ownerCount: number;
  equippedNow: number;
}

interface CosmeticsResponse { cosmetics: DashCosmetic[]; generatedAt: string }
type FetchResult = CosmeticsResponse | { error: string };

const CATEGORY_ICON: Record<string, string> = {
  hat: '🎩', glasses: '🕶️', aura: '🌟', board: '🏄', particle: '✦',
  palette: '🎨', outfit: '👕', default: '✨',
};

const RARITY_COLOR: Record<string, string> = {
  common: 'text-slate-300',
  rare:   'text-cyan-300',
  epic:   'text-violet-300',
  limited:'text-amber-300',
};

async function fetchCosmetics(): Promise<FetchResult> {
  const apiBase = process.env.NEXT_PUBLIC_API_URL ?? '';
  if (!apiBase) return { error: 'NEXT_PUBLIC_API_URL is not configured.' };
  const cookieStore = await cookies();
  try {
    const res = await fetch(`${apiBase}/api/dashboard/cosmetics`, {
      headers: { cookie: cookieStore.toString() },
      cache: 'no-store',
    });
    if (res.status === 401) return { error: 'Not authenticated. Sign in as an admin first.' };
    if (res.status === 403) return { error: 'Your account is not in ADMIN_USER_IDS.' };
    if (!res.ok) return { error: `API returned ${res.status}.` };
    return (await res.json()) as CosmeticsResponse;
  } catch (err) {
    return { error: `Fetch failed: ${String(err)}` };
  }
}

export default async function CosmeticsTab() {
  const data = await fetchCosmetics();
  if ('error' in data) {
    return <div className="rounded border border-red-500/30 bg-red-500/5 p-4 text-sm text-red-300">{data.error}</div>;
  }

  const byCategory = data.cosmetics.reduce<Record<string, DashCosmetic[]>>((acc, c) => {
    (acc[c.category] ??= []).push(c);
    return acc;
  }, {});

  return (
    <div className="space-y-8">
      <section>
        <h2 className="mb-1 text-lg font-semibold">Cosmetic catalog</h2>
        <p className="mb-3 text-xs font-mono text-slate-500">
          {data.cosmetics.length} SKUs total · scope-aware (world / avatar / activity:reef-race / activity:bumper-shells / all) ·
          thumbnails generated by <code>scripts/generate-cosmetic-thumbnail.mjs</code>; category-icon fallback when null
        </p>

        {data.cosmetics.length === 0 ? (
          <div className="rounded border border-slate-700/50 bg-slate-900/30 p-6 text-center">
            <p className="font-mono text-xs text-slate-400">Catalog is empty.</p>
            <p className="mt-2 text-xs text-slate-500">
              First content drop = the 4 surfboards from the Reef Race v2 session.
              Seed via cosmetic_skus + cosmetic_variants insert + run the
              thumbnail script.
            </p>
          </div>
        ) : (
          Object.entries(byCategory).map(([cat, items]) => (
            <div key={cat} className="mt-5">
              <h3 className="mb-2 font-mono text-[11px] uppercase tracking-[0.18em] text-slate-400">
                {CATEGORY_ICON[cat] ?? CATEGORY_ICON.default} {cat} ({items.length})
              </h3>
              <div className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-4">
                {items.map((c) => (
                  <CosmeticCard key={c.id} c={c} />
                ))}
              </div>
            </div>
          ))
        )}
      </section>
    </div>
  );
}

function CosmeticCard({ c }: { c: DashCosmetic }) {
  const icon = CATEGORY_ICON[c.category] ?? CATEGORY_ICON.default;
  const rarityClass = RARITY_COLOR[c.rarity] ?? 'text-slate-300';
  const isLimited = !!c.availableUntil;
  return (
    <div className={`rounded border bg-slate-900/30 p-3 ${isLimited ? 'border-amber-400/30' : 'border-slate-700/50'}`}>
      <div className="flex aspect-square items-center justify-center rounded bg-black/30">
        {c.thumbnailUrl ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img src={c.thumbnailUrl} alt={c.displayName} className="h-full w-full rounded object-contain" />
        ) : (
          <span className="text-3xl" aria-hidden>{icon}</span>
        )}
      </div>
      <h4 className="mt-2 truncate font-mono text-[11px] uppercase tracking-[0.16em] text-slate-200" title={c.displayName}>
        {c.displayName}
      </h4>
      <div className="mt-1 flex flex-wrap gap-x-2 gap-y-0.5 font-mono text-[9px] uppercase tracking-[0.18em]">
        <span className={rarityClass}>{c.rarity}</span>
        <span className="text-slate-500">·</span>
        <span className="text-slate-400">{c.scope}</span>
      </div>
      <div className="mt-2 flex flex-wrap gap-x-2 gap-y-0.5 font-mono text-[10px]">
        <span className="text-amber-300">{c.priceCt} CT{c.exclusiveCurrency === 'CLV' ? ' ($CLAWVILLE-only)' : ''}</span>
      </div>
      <div className="mt-1 font-mono text-[9px] text-slate-500">
        {c.variantCount} variant{c.variantCount === 1 ? '' : 's'} · {c.ownerCount} owner{c.ownerCount === 1 ? '' : 's'} · {c.equippedNow} equipped
      </div>
      {c.attribution ? (
        <a
          href={c.attributionUrl ?? '#'}
          target={c.attributionUrl ? '_blank' : undefined}
          rel="noreferrer"
          className="mt-2 block truncate font-mono text-[9px] text-slate-500 hover:text-slate-300"
          title={c.attribution}
        >
          {c.attribution}
        </a>
      ) : null}
    </div>
  );
}
