import {
  pgTable,
  uuid,
  text,
  varchar,
  integer,
  boolean,
  timestamp,
  index,
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { activities } from './activities';

/**
 * Q2 Activity Portals §7 — one row per match.
 *
 * Persisted on PENDING → COUNTDOWN transition (the "this match existed"
 * commit). `started_at` is set when COUNTDOWN → LIVE; `ended_at` when
 * LIVE → RESULTS. Status values match the room-FSM:
 *   'countdown' | 'live' | 'completed' | 'aborted' | 'aborted_crash'
 *
 * `short_code` is a 6-char base32-crockford code used for invite-share
 * deep-linking. Unique across all live rooms; collisions on insert are
 * regenerated by the room manager before persistence.
 *
 * Indexes:
 *   (activity_id, created_at DESC) — recent matches per activity
 *   (status) WHERE status IN ('countdown','live') — orphan sweep on boot
 */
export const activityRooms = pgTable(
  'activity_rooms',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    activityId: text('activity_id')
      .notNull()
      .references(() => activities.id),
    /** 6-char base32-crockford share code (unique per live room) */
    shortCode: varchar('short_code', { length: 10 }).notNull().unique(),
    /** 'countdown' | 'live' | 'completed' | 'aborted' | 'aborted_crash' */
    status: text('status').notNull(),
    playerCount: integer('player_count').notNull(),
    hasBots: boolean('has_bots').notNull().default(false),
    hasAgents: boolean('has_agents').notNull().default(false),
    startedAt: timestamp('started_at', { withTimezone: true }),
    endedAt: timestamp('ended_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    activityCreatedIdx: index('idx_activity_rooms_activity_created').on(
      t.activityId,
      t.createdAt.desc(),
    ),
    activeStatusIdx: index('idx_activity_rooms_active_status')
      .on(t.status)
      .where(sql`status IN ('countdown','live')`),
  }),
);

export type ActivityRoom = typeof activityRooms.$inferSelect;
export type NewActivityRoom = typeof activityRooms.$inferInsert;
