/**
 * Public skills API — serves agentskills.io-compatible SKILL.md files from
 * the `building_skills` table. Content is pre-generated by
 * `scripts/generate-building-skills.ts` — no per-request LLM calls.
 *
 * Routes:
 *   GET /api/skills                        — JSON index of all skills
 *   GET /api/skills/:buildingId/skill.md   — raw SKILL.md (text/markdown)
 *   GET /api/skills/:buildingId            — JSON metadata for a single skill
 */

import { Hono } from 'hono';
import { db, buildingSkills, eq } from '@clawville/database';
import { logEventFromContext } from '../services/event-logger';
import type { AppContext } from '../types';

export const skillsRoutes = new Hono<AppContext>();

skillsRoutes.get('/', async (c) => {
  const rows = await db
    .select({
      buildingId: buildingSkills.buildingId,
      name: buildingSkills.name,
      description: buildingSkills.description,
      generatedAt: buildingSkills.generatedAt,
      generatorVersion: buildingSkills.generatorVersion,
    })
    .from(buildingSkills);

  return c.json({
    count: rows.length,
    skills: rows.map((r) => ({
      ...r,
      skillUrl: `/api/skills/${r.buildingId}/skill.md`,
    })),
  });
});

skillsRoutes.get('/:buildingId/skill.md', async (c) => {
  const buildingId = c.req.param('buildingId');
  const [row] = await db
    .select()
    .from(buildingSkills)
    .where(eq(buildingSkills.buildingId, buildingId))
    .limit(1);

  if (!row) {
    return c.text(`# Not found\n\nNo skill registered for "${buildingId}".\n`, 404, {
      'Content-Type': 'text/markdown; charset=utf-8',
    });
  }

  void logEventFromContext(c, {
    eventType: 'skill_md.fetched',
    buildingId,
    agentId: c.req.header('x-clawville-agent-id') ?? null,
    sessionId: c.req.header('x-clawville-session-id') ?? null,
    payload: {
      userAgent: c.req.header('user-agent') ?? null,
      referer: c.req.header('referer') ?? null,
      skillName: row.name,
      generatorVersion: row.generatorVersion,
    },
  });

  return new Response(row.content, {
    status: 200,
    headers: {
      'Content-Type': 'text/markdown; charset=utf-8',
      'Cache-Control': 'public, max-age=300',
      'X-Skill-Name': row.name,
      'X-Skill-Version': String(row.generatorVersion),
    },
  });
});

skillsRoutes.get('/:buildingId', async (c) => {
  const buildingId = c.req.param('buildingId');
  const [row] = await db
    .select({
      buildingId: buildingSkills.buildingId,
      name: buildingSkills.name,
      description: buildingSkills.description,
      generatedAt: buildingSkills.generatedAt,
      generatorVersion: buildingSkills.generatorVersion,
      sourceArticleIds: buildingSkills.sourceArticleIds,
    })
    .from(buildingSkills)
    .where(eq(buildingSkills.buildingId, buildingId))
    .limit(1);

  if (!row) {
    return c.json({ error: 'skill_not_found', buildingId }, 404);
  }

  return c.json({
    ...row,
    skillUrl: `/api/skills/${row.buildingId}/skill.md`,
  });
});
