/**
 * Public skills API — serves agentskills.io-compatible SKILL.md files from
 * the `building_skills` table. Content is pre-generated by
 * `scripts/generate-building-skills.ts` — no per-request LLM calls.
 *
 * Routes:
 *   GET /api/skills                        — JSON index of all skills
 *   GET /api/skills/:buildingId/skill.md   — raw SKILL.md (gated, see below)
 *   GET /api/skills/:buildingId            — JSON metadata for a single skill
 *
 * Inventory gating (added 2026-05-03)
 *   --------------------------------
 *   Per-building SKILL.md content is the *paid* curriculum — it lives behind
 *   ownership so agents can't reverse-engineer the URL pattern and fetch
 *   skills they never bought. Two ways to satisfy ownership:
 *
 *   1. Authenticated browser session (Lucia cookie) — the user's avatar must
 *      have at least one knowledge entry from this building's books.
 *   2. Authenticated agent session (Bearer sessionId) — the agent's linked
 *      avatar must have at least one knowledge entry from this building's
 *      books. (Same check, different auth path.)
 *
 *   Unauthenticated callers and authed callers without ownership get 402
 *   Payment Required + a metadata-only teaser body. The `clawville-play`
 *   meta skill is the one exception — it's the entry-point skill any
 *   agent needs before they can play, so it stays public.
 */

import { Hono } from 'hono';
import { db, buildingSkills, openclawBots, avatars, eq, and } from '@clawville/database';
import { getBooksForBuilding, BUILDING_OPENCLAW_THEMES } from '@clawville/shared';
import { lucia } from '../lib/auth';
import { logEventFromContext } from '../services/event-logger';
import type { AppContext } from '../types';

export const skillsRoutes = new Hono<AppContext>();

skillsRoutes.get('/', async (c) => {
  const rows = await db
    .select({
      buildingId: buildingSkills.buildingId,
      name: buildingSkills.name,
      description: buildingSkills.description,
      generatedAt: buildingSkills.generatedAt,
      generatorVersion: buildingSkills.generatorVersion,
    })
    .from(buildingSkills);

  return c.json({
    count: rows.length,
    skills: rows.map((r) => ({
      ...r,
      skillUrl: `/api/skills/${r.buildingId}/skill.md`,
    })),
  });
});

/**
 * Resolve the caller's avatar ID via either Lucia session cookie or
 * Authorization: Bearer <agent-sessionId>. Returns null if both fail.
 */
async function resolvePetId(c: any): Promise<string | null> {
  // Try Lucia session cookie first
  const cookieHeader = c.req.header('Cookie');
  if (cookieHeader) {
    const cookieName = lucia.sessionCookieName;
    const sessionMatch = cookieHeader.match(new RegExp(`${cookieName}=([^;]+)`));
    if (sessionMatch) {
      try {
        const { user } = await lucia.validateSession(sessionMatch[1]);
        if (user) {
          const row = await db.query.avatars.findFirst({
            where: and(eq(avatars.userId, user.id), eq(avatars.isActive, true)),
            columns: { id: true },
          });
          if (row) return row.id;
        }
      } catch {
        /* fall through to bearer */
      }
    }
  }

  // Try agent Bearer sessionId — sessionId itself is opaque, so we look up
  // the openclaw_bots row by agent_id matching the in-memory map. Cheap
  // alternative: skip sessionId resolution entirely and take agent_id from
  // the X-Clawville-Agent-Id header that nanoclaw clients already send for
  // event logging.
  const auth = c.req.header('Authorization');
  const agentIdHeader = c.req.header('X-Clawville-Agent-Id');
  if (auth?.startsWith('Bearer ') || agentIdHeader) {
    // Prefer agent-id header (set by nanoclaw harnesses); fall back to the
    // session-resolution map for sessionId-only callers.
    const { npcSimulation } = await import('../services/npc-simulation');
    let agentId: string | null = agentIdHeader ?? null;
    if (!agentId && auth) {
      const sid = auth.slice(7);
      const cfg = npcSimulation.getOpenClawBotConfig(sid);
      agentId = cfg?.agentId ?? null;
    }
    if (agentId) {
      const bot = await db.query.openclawBots.findFirst({
        where: eq(openclawBots.agentId, agentId),
        columns: { userId: true },
      });
      if (bot?.userId) {
        const avatar = await db.query.avatars.findFirst({
          where: and(eq(avatars.userId, bot.userId), eq(avatars.isActive, true)),
          columns: { id: true },
        });
        if (avatar) return avatar.id;
      }
    }
  }

  return null;
}

/**
 * Returns true if the avatar's characterConfig.knowledge contains at least
 * one entry from any of the building's books' knowledgeEntries arrays.
 * This matches the in-game definition of "you've read at least one book
 * here" — the install moment, not just visiting.
 */
async function petOwnsBuilding(avatarId: string, buildingId: string): Promise<boolean> {
  const row = await db.query.avatars.findFirst({
    where: eq(avatars.id, avatarId),
    columns: { characterConfig: true },
  });
  const known: string[] =
    (row?.characterConfig as { knowledge?: string[] } | null)?.knowledge ?? [];
  if (known.length === 0) return false;
  const knownSet = new Set(known);
  for (const book of getBooksForBuilding(buildingId)) {
    for (const entry of book.knowledgeEntries) {
      if (knownSet.has(entry)) return true;
    }
  }
  return false;
}

function teaserBody(buildingId: string, skillName: string, description: string): string {
  const theme = BUILDING_OPENCLAW_THEMES[buildingId];
  const label = theme?.label ?? buildingId;
  return [
    '---',
    `name: ${skillName}`,
    `description: ${description}`,
    `version: 0.0.0`,
    'license: gated',
    `metadata:`,
    `  building_id: ${buildingId}`,
    `  building_label: ${JSON.stringify(label)}`,
    `  ownership: locked`,
    '---',
    '',
    `# ${label} — locked`,
    '',
    `This skill is gated. To unlock, your avatar must read at least one knowledge`,
    `book from the ${label} in ClawVille. Path:`,
    '',
    `1. Connect (or sign in) at https://clawville.world.`,
    `2. Visit ${label} (\`buildingId: ${buildingId}\`).`,
    `3. Buy and read a knowledge book at the shop.`,
    `4. Refetch this URL via your authed agent session — the SKILL.md`,
    `   contents will appear in full and your harness will receive a`,
    `   \`knowledge_added\` SSE event with the install URL.`,
    '',
    `(This is a metadata-only teaser. The full ${skillName} content is`,
    `available once you own it.)`,
    '',
  ].join('\n');
}

skillsRoutes.get('/:buildingId/skill.md', async (c) => {
  const buildingId = c.req.param('buildingId');
  const [row] = await db
    .select()
    .from(buildingSkills)
    .where(eq(buildingSkills.buildingId, buildingId))
    .limit(1);

  if (!row) {
    return c.text(`# Not found\n\nNo skill registered for "${buildingId}".\n`, 404, {
      'Content-Type': 'text/markdown; charset=utf-8',
    });
  }

  // Entry-point skill: always public so agents can install the play loop
  // before they own anything.
  const isEntrySkill = buildingId === 'clawville-play';

  let unlocked = isEntrySkill;
  if (!unlocked) {
    const avatarId = await resolvePetId(c);
    if (avatarId) {
      unlocked = await petOwnsBuilding(avatarId, buildingId);
    }
  }

  if (!unlocked) {
    return c.text(teaserBody(buildingId, row.name, row.description), 402, {
      'Content-Type': 'text/markdown; charset=utf-8',
      'X-Skill-Locked': 'true',
      'X-Skill-Building': buildingId,
    });
  }

  void logEventFromContext(c, {
    eventType: 'skill_md.fetched',
    buildingId,
    agentId: c.req.header('x-clawville-agent-id') ?? null,
    sessionId: c.req.header('x-clawville-session-id') ?? null,
    payload: {
      userAgent: c.req.header('user-agent') ?? null,
      referer: c.req.header('referer') ?? null,
      skillName: row.name,
      generatorVersion: row.generatorVersion,
      gated: !isEntrySkill,
    },
  });

  return new Response(row.content, {
    status: 200,
    headers: {
      'Content-Type': 'text/markdown; charset=utf-8',
      'Content-Disposition': `attachment; filename="clawville-${buildingId}.md"`,
      'Cache-Control': 'private, max-age=60',
      'X-Skill-Name': row.name,
      'X-Skill-Filename': `clawville-${buildingId}.md`,
      'X-Skill-Version': String(row.generatorVersion),
      'Access-Control-Expose-Headers': 'Content-Disposition, X-Skill-Name, X-Skill-Filename, X-Skill-Version',
    },
  });
});

skillsRoutes.get('/:buildingId', async (c) => {
  const buildingId = c.req.param('buildingId');
  const [row] = await db
    .select({
      buildingId: buildingSkills.buildingId,
      name: buildingSkills.name,
      description: buildingSkills.description,
      generatedAt: buildingSkills.generatedAt,
      generatorVersion: buildingSkills.generatorVersion,
      sourceArticleIds: buildingSkills.sourceArticleIds,
    })
    .from(buildingSkills)
    .where(eq(buildingSkills.buildingId, buildingId))
    .limit(1);

  if (!row) {
    return c.json({ error: 'skill_not_found', buildingId }, 404);
  }

  return c.json({
    ...row,
    skillUrl: `/api/skills/${row.buildingId}/skill.md`,
  });
});

// ---------------------------------------------------------------------------
// POST /api/skills/forge  — chat conversation → custom installable skill
// ---------------------------------------------------------------------------
// Take a transcript of an agent's conversation with a building teacher
// and distill it into a custom SKILL.md + tools.json the agent can
// install via the same pipeline as the canonical building skills. Lets
// users capture "I learned how to do X with Gary" as a permanent,
// portable skill artifact.
//
// STUB SHAPE — wired but does NOT yet run a Gemini distill pass. The
// route returns 501 with a structured payload describing the eventual
// response so the install pipeline at the harness side can be coded
// against the contract today. Implementation lands when the
// custom_skills table + Gemini distill prompt ship.
// ---------------------------------------------------------------------------
skillsRoutes.post('/forge', async (c) => {
  let body: any = {};
  try {
    body = await c.req.json();
  } catch {
    return c.json({ error: 'invalid_json' }, 400);
  }

  const buildingId = typeof body?.buildingId === 'string' ? body.buildingId : null;
  const conversationId = typeof body?.conversationId === 'string' ? body.conversationId : null;
  const turns = Array.isArray(body?.turns) ? body.turns : null;

  if (!buildingId) return c.json({ error: 'buildingId_required' }, 400);
  if (!conversationId && !turns) {
    return c.json({ error: 'conversationId_or_turns_required' }, 400);
  }

  return c.json(
    {
      status: 'implementation_pending',
      message:
        'Conversation→skill distillation is not yet wired. Endpoint shape is stable so harnesses can code against the contract.',
      expectedResponseShape: {
        ok: true,
        skillId: '<uuid>',
        skillName: '<derived-from-conversation>',
        suggestedFilename: 'clawville-custom-<slug>.md',
        skillUrl: '/api/skills/forge/<skillId>/skill.md',
        toolsUrl: '/api/skills/forge/<skillId>/tools.json',
        toolsFilename: 'clawville-custom-<slug>.tools.json',
        sourceConversationId: '<conversationId>',
        sourceBuildingId: '<buildingId>',
      },
      receivedRequest: { buildingId, conversationId, turnCount: turns?.length ?? null },
    },
    501,
  );
});
