/**
 * Seed the production-exported building skill fixture into staging or dev.
 *
 * By default this never updates an existing row: generated or manually
 * corrected database content wins, while an empty environment receives the
 * same ten building manuals without making any LLM or network request. Pass
 * `--update-content` to update an existing row only when its content hash has
 * changed in the fixture.
 * `clawville-play` is code-generated by the API and must not be seeded here.
 */
import { createHash } from 'node:crypto';
import { config } from 'dotenv';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SHOP_BUILDINGS } from '@clawville/shared';
import fixtureJson from './fixtures/building-skills.json';

config({ path: resolve(fileURLToPath(new URL('.', import.meta.url)), '../.env.local') });

interface BuildingSkillFixtureRow {
  building_id: string;
  name: string;
  description: string;
  content: string;
  content_hash: string;
  generator_version: number;
  source_article_ids: string[];
}

function isFixtureRow(value: unknown): value is BuildingSkillFixtureRow {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return false;
  const row = value as Record<string, unknown>;
  return (
    typeof row.building_id === 'string' &&
    row.building_id.length > 0 &&
    typeof row.name === 'string' &&
    row.name.length > 0 &&
    typeof row.description === 'string' &&
    row.description.length > 0 &&
    typeof row.content === 'string' &&
    row.content.length > 0 &&
    typeof row.content_hash === 'string' &&
    /^[a-f0-9]{64}$/.test(row.content_hash) &&
    Number.isInteger(row.generator_version) &&
    Array.isArray(row.source_article_ids) &&
    row.source_article_ids.every((id) => typeof id === 'string')
  );
}

function parseFixture(value: unknown): BuildingSkillFixtureRow[] {
  if (!Array.isArray(value) || value.length !== 10 || !value.every(isFixtureRow)) {
    throw new Error('building-skills fixture must contain exactly 10 valid rows');
  }

  const ids = new Set(value.map((row) => row.building_id));
  if (ids.size !== value.length) {
    throw new Error('building-skills fixture contains duplicate building_id values');
  }
  if (ids.has('clawville-play')) {
    throw new Error('clawville-play is code-generated and must not be in the DB fixture');
  }
  for (const row of value) {
    const derivedHash = createHash('sha256').update(row.content).digest('hex');
    if (row.content_hash !== derivedHash) {
      throw new Error(`building-skills fixture has an invalid content_hash for ${row.building_id}`);
    }
  }
  const canonicalIds = new Set<string>(SHOP_BUILDINGS);
  if (
    canonicalIds.size !== value.length ||
    value.some((row) => !canonicalIds.has(row.building_id))
  ) {
    throw new Error('building-skills fixture IDs must match the canonical 10 buildings');
  }
  return value;
}

async function main(): Promise<void> {
  const fixture = parseFixture(fixtureJson);
  const updateContent = process.argv.slice(2).includes('--update-content');
  // Keep the database module behind dotenv initialization. This makes the
  // documented local `.env.local` invocation reliable even if database module
  // initialization becomes eager in the future.
  const { db, buildingSkills, sql } = await import('@clawville/database');
  const values = fixture.map((row) => ({
    buildingId: row.building_id,
    name: row.name,
    description: row.description,
    content: row.content,
    contentHash: row.content_hash,
    sourceArticleIds: row.source_article_ids,
    generatorVersion: row.generator_version,
    generatedAt: new Date(),
  }));

  if (updateContent) {
    const changed = await db
      .insert(buildingSkills)
      .values(values)
      .onConflictDoUpdate({
        target: buildingSkills.buildingId,
        set: {
          name: sql`excluded.name`,
          description: sql`excluded.description`,
          content: sql`excluded.content`,
          contentHash: sql`excluded.content_hash`,
          generatorVersion: sql`excluded.generator_version`,
          generatedAt: sql`excluded.generated_at`,
        },
        setWhere: sql`${buildingSkills.contentHash} is distinct from excluded.content_hash`,
      })
      .returning({ buildingId: buildingSkills.buildingId });

    console.log(
      `building_skills fixture: inserted or updated ${changed.length}, kept ${fixture.length - changed.length} hash-matching existing`,
    );
    return;
  }

  const inserted = await db
    .insert(buildingSkills)
    .values(values)
    .onConflictDoNothing({ target: buildingSkills.buildingId })
    .returning({ buildingId: buildingSkills.buildingId });

  console.log(
    `building_skills fixture: inserted ${inserted.length}, kept ${fixture.length - inserted.length} existing`,
  );
}

main()
  .then(() => process.exit(0))
  .catch((error: unknown) => {
    console.error(
      `building_skills fixture failed: ${error instanceof Error ? error.message : String(error)}`,
    );
    process.exit(1);
  });
