export {
  KELP_FOREST_PORTAL_ID,
  KELP_FOREST_PORTAL_PROMPT_RADIUS_WU,
  KELP_FOREST_PORTAL_WORLD_CENTER as KELP_FOREST_CENTER,
  KELP_FOREST_PORTAL_APPROACH_WORLD as KELP_FOREST_EXIT_WORLD,
} from '@clawville/shared';
