/**
 * Generates apps/api/src/services/floor-arena/confusables.generated.ts from Unicode's official
 * confusables.txt (UTS #39), for the arena's reserved-name check (names.ts, Codex r20).
 *
 *   bun apps/api/scripts/floor-arena/generate-confusables.ts              # fetches SOURCE_URL
 *   bun apps/api/scripts/floor-arena/generate-confusables.ts <file.txt>   # reads a local copy
 *
 * Each prototype is cleaned the way names.ts cleans a player's name: NFD, combining marks removed,
 * then every character that is not a letter or digit removed (Codex r21: Ɠ has the prototype "G'",
 * and the name key drops the apostrophe too). Kept: every source character whose cleaned prototype
 * is not empty and is made only of ASCII letters or digits and keys of FLOOR_ARENA_EXTRA_FOLDS
 * (name-folds.ts), for example Greek capital Nu -> N, Cherokee letter NAH -> G, digit zero -> O,
 * m -> rn, Ɠ -> G, Cyrillic small en -> ʜ (which names.ts then folds to h). Any other prototype is
 * left out, because the house names are ASCII and such a source can never read as one. Output is
 * sorted by code point. Re-run after any change to FLOOR_ARENA_EXTRA_FOLDS; the generated file
 * records the keys it used.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FLOOR_ARENA_EXTRA_FOLDS } from '../../src/services/floor-arena/name-folds';

const SOURCE_URL = 'https://www.unicode.org/Public/security/latest/confusables.txt';
const OUT = join(dirname(fileURLToPath(import.meta.url)), '../../src/services/floor-arena/confusables.generated.ts');

function fromHex(field: string): string {
  return field.trim().split(/\s+/).map((hex) => String.fromCodePoint(Number.parseInt(hex, 16))).join('');
}

const EXTRA_KEYS = Object.keys(FLOOR_ARENA_EXTRA_FOLDS).sort();
const extraKeys = new Set(EXTRA_KEYS);

/** ASCII letters and digits as they are, every other character as a \u{...} escape (the file stays ASCII). */
function escapeKey(text: string): string {
  return [...text].map((ch) => (/^[A-Za-z0-9]$/.test(ch) ? ch : `\\u{${ch.codePointAt(0)!.toString(16).toUpperCase()}}`)).join('');
}

const text = process.argv[2]
  ? readFileSync(process.argv[2], 'utf8')
  : await (await fetch(SOURCE_URL)).text();
const version = /^# Version: (.+)$/m.exec(text)?.[1]?.trim();
const date = /^# Date: (.+)$/m.exec(text)?.[1]?.trim();
if (!version || !date) throw new Error('confusables.txt header has no Version or Date line');

const entries: Array<[string, string]> = [];
for (const line of text.split('\n')) {
  if (!/^[0-9A-F]/.test(line)) continue;
  const [sourceHex, targetHex] = line.split(';');
  if (!sourceHex || !targetHex) continue;
  const source = fromHex(sourceHex);
  // Cleaned like the name key: NFD, no combining marks, letters and digits only.
  const target = fromHex(targetHex).normalize('NFD').replace(/\p{M}/gu, '').replace(/[^\p{L}\p{N}]/gu, '');
  if (target.length > 0 && [...target].every((ch) => /^[A-Za-z0-9]$/.test(ch) || extraKeys.has(ch))) entries.push([source, target]);
}
entries.sort((a, b) => a[0].codePointAt(0)! - b[0].codePointAt(0)!);

const rows: string[] = [];
for (let i = 0; i < entries.length; i += 6) {
  rows.push(`  ${entries.slice(i, i + 6).map(([s, t]) => `'${escapeKey(s)}': '${escapeKey(t)}',`).join(' ')}`);
}

writeFileSync(OUT, `// GENERATED by apps/api/scripts/floor-arena/generate-confusables.ts. Do not edit by hand; re-run it.
// Source: ${SOURCE_URL}
// Unicode Security Mechanisms for UTS #39, Version: ${version}, Date: ${date}
// Unicode data, terms of use: https://www.unicode.org/terms_of_use.html
// Kept: source characters whose prototype, after NFD, removal of combining marks and removal of
// every non-letter/digit (as the name key does), is not empty and is made only of ASCII letters or
// digits and keys of FLOOR_ARENA_EXTRA_FOLDS (name-folds.ts).
// ${entries.length} entries, keyed by the exact source character.

export const FLOOR_ARENA_CONFUSABLES_VERSION = '${version}';
export const FLOOR_ARENA_CONFUSABLES_DATE = '${date}';
/** The FLOOR_ARENA_EXTRA_FOLDS keys this file was generated with (a test pins them in sync). */
export const FLOOR_ARENA_CONFUSABLES_EXTRA_KEYS: readonly string[] = Object.freeze([${EXTRA_KEYS.map((k) => `'${escapeKey(k)}'`).join(', ')}]);

export const FLOOR_ARENA_CONFUSABLES: Readonly<Record<string, string>> = Object.freeze({
${rows.join('\n')}
});
`);
console.log(`wrote ${entries.length} entries (Unicode ${version}, ${date}) to ${OUT}`);
